### ISSUE TITLE
XEP-0322 support - Efficient XML Interchange (EXI) Format

### ISSUE THREAD

**Issue by devurandom** [iNPUTmice/Conversations#1001]
[XEP-0322](http://xmpp.org/extensions/xep-0322.html): "The Efficient XML Interchange (EXI) Format [1] is an efficient way to compress XML documents and XML fragments. This document provides information on how EXI can be used in XMPP streams to efficiently compress data transmitted between the server and the client."

Support for this seems to be very interesting for a mobile client. Server support appears to be currently lacking, though. Maybe this will change soon, as the XEP was a key item on the XMPP Summit 17 (held just a few weeks ago): http://xmpp.org/2015/01/xmpp-summit-17/

Bugtracker items for other clients:
- https://igniterealtime.org/issues/browse/SMACK-611
- https://developer.pidgin.im/ticket/15598

Bugtracker items for servers:
- esl/MongooseIM#145
- https://prosody.im/issues/issue/628

**Comment by iNPUTmice** [comment]
There is a java library that should run on Android and also should work with our XML parser https://github.com/EXIficient/exificient

**Comment by Protagores** [comment]
Implementing this would certainly make a difference for those who connect over legacy 2G GPRS/EDGE networks, especially in remote regions where there's no faster alternative available. The lags which come with the overhead of sending large textually represented XMPP packets over such slow networks is often a show stopper, causing the use of a proprietary messenger to be the only viable option because of exactly this. I'd pretty much like to see it addressed by supporting this XEP in clients and servers ASAP.

**Comment by guusdk** [comment]
Leaving this here as it's a prominent search result when searching for 'XMPP' and 'EXI'. 

Nowadays, Openfire has server-sided support for EXI. It got introduced here: https://discourse.igniterealtime.org/t/developing-openfire-efficient-xml-interchange-exi-functionality
