### ISSUE TITLE
OMEMO long fingerprints

### ISSUE THREAD

**Issue by knoy** [iNPUTmice/Conversations#1390]
As OMEMO is based on the Axolotl ratchet and uses ECC (Curve25519 specifically) I'm unsure why the fingerprints listed in the accounts section are so long? Shouldn't a fingerprint half that size be sufficient in entropy ? Long fingerprints hurt usability and make verification more difficult

**Comment by strb** [comment]
We're using the libaxolotl-java [getFingerprint()](https://github.com/WhisperSystems/libaxolotl-java/blob/master/java/src/main/java/org/whispersystems/libaxolotl/IdentityKey.java#L50) function, which basically just returns the hex-encoded public key (prefixed with a curve type tag, which is why they all start with 0x05). It looks basically the same in [TextSecure](https://securityinabox.org/sites/siabnext.ttc.io/files/media/textsecure_045.png).This could maybe be shortened by displaying a hash thereof, but this wasn't done (yet?) for simplicity reasons. But you're not wrong, this might be worth thinking about.

**Comment by knoy** [comment]
This should be a truncated SHA-256 or maybe a SHA-224 I think. Perhaps Moxie's original idea was to stay as far away from the PGP practice of using dramatically truncated SHA1 hashes (which already has collision attacks) but this is just a little over the top.

**Comment by singpolyma** [comment]
Could use a word-encoding like mnmonicode (which I did not develop, but currently maintain) which seems to improve usability for some users.

**Comment by knoy** [comment]
Where is this project? I didn't get any google results for "mnmonicode"

Word encoding can work however it can introduce localization problems for non-english speakers

**Comment by singpolyma** [comment]
Hmm, yes, I do see how localisation issues might come up: https://github.com/singpolyma/mnemonicode

**Comment by knoy** [comment]
I think the first 32 chars of SHA-512 would be a reasonable security/useability tradeoff. This should offer at least 128-bits (4 * 32) of security and would be half the size of the current fingerprint.

Additionally if we used a human-readable base32 alphabet such as RFC 4648 or z-base-32 instead of hex to encode the hash (https://en.wikipedia.org/wiki/Base32) we could double the security to 256-bits.

32 characters could be seperated into 4 rows of 8 characters. We could use additional unused bits of the hash to modify the colours for each row, say 8 different colours (8 * 4 = 32 additional bits of security).

If OMEMO implements all these suggestions it would provide roughly 288-bits of security. This would mean it could theoretically only be cracked in 2^144 time which is extremely large. In comparison to the best collision attack against SHA-1 (2^60 time) this should be extremely strong

**Comment by knoy** [comment]
Additionally, if the curve type is only one of a handful allowed by OMEMO I think it should be moved to the end of the fingerprint as it's unlikely to change much and the first few characters of a fingerprint are often the only ones that are actually compared

**Comment by knoy** [comment]
I just thought of a better, simpler alternative... just take the 64-char hex key we currently serve, base32 encode it so it shrinks to 32 chars. Then use the curve type to colour the key or append it to the end.

This way we don't use a hashing function at all and don't have to worry about future collision attacks

**Comment by iNPUTmice** [comment]
Yes I generally agree with stripping the 0x05 prefix. Since we explicitly mention the use of axolotl v3 in our XEP and axololt v3 doesn't specify any other curves this wouldn't lead to the loss of information.

and using base32 instead of hex might be a nice idea as well. will think about that.

(Even if the curves get updated for axololt v4 / OMEMO v 2 we could just put the curve information in the footer and call it OMEMO v2 fingerprint instead of OMEMO fingerprint)

**Comment by gaelsano** [comment]
@knoy Base32 is 5 bits per character. Hexadecimal is 4 bits per character. So, a 64-character hex sequence would be 256 bits. That means the Base32 version would be 52 characters. That would be 260 bits, which usually means there will be a few padding =, however, we could drop that. The last Base32 character will end in four zeroes.

Base32 is a great idea, as is dropping the curve info--but using a hash of the key makes the curve info byte unnecessary anyway.

I suggest we use a SHA-1 fingerprint of the key, truncated to 100 bits, and encoded in Base32 (5 bits per character) in 20 characters. Seems to be the best trade-off between security and convenience.

We don't need the total length of the ECC keys, since 256 bits are only good for 128 bits of security.

We do not have to consider birthday attacks for the keys, since keys are self-verified. The only times you need to worry about birthday attacks is with signatures and third-party verifications.
(Example 1: you type two contracts. One is fair and one is unfair. You add random data to each until you hit a collision when they're hashed. You send the fair one to me and ask me to sign it. I sign it. You then copy-paste my signature onto the unfair contract.)
(Example 2: You write a new program and the same program with a few lines of malware. You add data until you get a hash collision. You send the source code of the clean program to me for auditing. I say the code is good. I tell my friends that if they download your_program.tar.xz with the hash of ....... then it is good. You then upload your_program-with_malware.tar.xz onto your github page.)

We also do not have to take into account quantum computing attacks. A basic verification hash would need to be longer, like SHA224 or longer, to be quantum proof.

However, since quantum computing would render DSA, RSA, and ECC keys useless very quickly, a quantum-proof hash is wholly unnecessary.

(n is number of bits. "security" is the 50% probability of success with brute force, i.e. the tipping point)
1. Pre-image attacks cannot bring down security. Security is n-1. A hash of 300 bits is 2999 bits strong.
2. Collision attacks bring security to n/2. A hash of 300 bits is 150 bits strong.
3. Chosen prefix collision attacks bring security to (n/2)+1 because your collisions have to occur in two different sets. I.e., you need a collision that is between a fair and an unfair contract--not a fair and a fair contract or an unfair and an unfair contract. A hash of 300 bits is 151 bits strong.
4. Quantum pre-image attacks halve the security, n/2. A hash of 300 bits is 150 bits strong.
5. Quantum birthday attacks make values a third as strong, n/3. A hash of 300 bits is 100 bits strong.

We only need to worry about scenario 1. SHA-1 has 160 bits. It is flawed against collision attacks, with just 73 bits (instead of 80 bits) of security. However, that is okay. It is not flawed with regards to pre-image attacks, where it has 159 bits of security, since odds are that you will be successful in brute force attacks after 2^(n-1) attempts.

AES is flawed actually. AES128 offers 126.1 bits of keyspace and AES256 offers 254.4 bits of keyspace, which are effectively 125.1 and 253.4 bits of security.

Neither is in danger at all. No one is saying we must replace them.

SHA-1 is totally fine to use.

Even a truncated SHA is fine to use.

100 bits of SHA-1 in 20 characters of Base32 gives us 99 bits of security.

WhatApp's fingerprints are represented in 30 digits of Base10 or QR code. log2(10^30) is equal to 2^99.7, which means 99.7 bits of space or 98.7 bits of security against brute force attacks.

So, we would still have better security than Whatsapp. The one thing in Whatsapp's favor is that is strictly numerical. While the internet and systems based on ASCII, etc, use A-Z and most or all symbols, many people who use other scripts (Han, arabic, etc) are unable to reliably distinguish a-z, get them mixed up, etc. (Experience here!) This is part of why the internationalized domain names are taking off. (I still oppose internationalized domain names because spoofing latin A and Cyrillic A is all too easy, but I can't deny how people love them and use them.)

So there is that to consider. Two friends who know and recognize each others' voices reading off their codes n voice chat or in a simple phone call need to be able to communicate. This is not the same as copying onion urls and pronounceability is important. ZRTP was dead on arrival when I tried teaching it to non-native English speakers. I'm glad it's not taking off. SAS words were only useful for English-speakers.

For equivalent and sufficient (?) security, thirty Base10 numbers or twenty Base32 characters.

**Comment by htgoebel** [comment]
pEp (pretty Easy privacy) introduces a concept of "trustwords" to overcome the fingerprints. The concept is similar but a bit different to mnemonicode: It uses 65536 words (so matching 16 bit) and words in different languages. The words are not specially selected, but simply taken from a dictionary with swearwords removed. See screenshot for an example.

The UI could have an option (e.g. a tab) to switch to hex-digits to be exchanged with other programs. And of course, this could be used for all types of fingerprints.

![Screenshot showing usage of Trustwords](https://cloud.githubusercontent.com/assets/784161/17886564/b08fae98-6922-11e6-8bce-613e02ce33d8.png)

https://cacert.pep.foundation/trac/browser/db contains word lists for ca, de, es, en, fr and tr. These lists are already cleaned from swearwords.

For more information see https://cacert.pep.foundation/trac/wiki/Trustwords (which may be a bit outdated) and get in contact with pEp.
