### ISSUE TITLE
Online Offline toggle state when using TLS

### ISSUE THREAD

**Issue by tcuje** [iNPUTmice/Conversations#1495]
I tried to use the app, but lost connection to the server. Checking the ManageAccountActivity showed me, that my Account state was offline. Disabling and enabling the account results in a short "online" and blinks later back to "offline" state.

I debugged into the application and found that the processStream function in eu.siacs.conversations.xmpp.XmppConnection.java is called three times. Once for the original tag and twice recursive during switch over to TLS.

Unfortunately this means that at the end of the tag parsing while loop it sets my account back to offline, because of the following lines:

``` Java
if (account.getStatus() == Account.State.ONLINE) {
  account. setStatus(Account.State.OFFLINE);
  if (statusListener != null) {
    statusListener.onStatusChanged(account);
  }
}
```

My stacktrace looks like:
processStream():386, XmppConnection
processStream():289, XmppConnection
switchOverToTls():565, XmppConnection
processStream():275, XmppConnection
connect():213, XmppConnection
run():262, XmppConnection
run():818, Thread

I'm not sure about the process here and don't know the standards, but I suppose to skip the code quoted above during recursive calls. When executed once the account is offline and the code above does no harm, but during the recursive calls it kicks me out... Maybe you can remove the code at all?

**Comment by iNPUTmice** [comment]
What server are you using?

**Comment by tcuje** [comment]
jabber.rwth-aachen.de

**Comment by iNPUTmice** [comment]
I have no problem logging into that server

**Comment by tcuje** [comment]
Please try to switch your device to flight mode for a few seconds and try again. On first connection it works for me too.

**Comment by iNPUTmice** [comment]
what version are you on by the way?

**Comment by tcuje** [comment]
I'm using the latest release 1.6.11

**Comment by iNPUTmice** [comment]
the recursion in itself shouldn't be a problem. that's expected behavior. as I said I can't reproduce this even with changing networks or going into airplane mode.

so you will basically have to debug this yourself. but I can try to help you with that. can you start of by posting the adb logcat output of a full connection cycle?
the trace isn't helping much because that's as I said expected behavior.

**Comment by iNPUTmice** [comment]
added some logging in 76828950ee6529a6da98af484507a48f992d9442

please upgrade to HEAD and try to provide an adb logcat

**Comment by tcuje** [comment]
Here we go. I cloned HEAD and started debugging, when the app came into foreground I clicked on "manage accounts" and got the same error as before. Here is my Logcat output in Verbose mode:
http://pastebin.com/AsqpG8K9

**Comment by iNPUTmice** [comment]
```eu.siacs.conversations D/conversations: xxxxxxxxxxx@jabber.rwth-aachen.de: last tag was </stream>```

That's the server just terminating the connection (closing the stream). You could try to contact the admins and get a server log for that. As the fetch bookmarks call is the first call that remains unanswered maybe that call is triggering an exception on the server? But that's pure speculation.

Two questions. Does the account work in other clients? Can you register a second account and see if that works. I'm asking because my account works just fine and if the exception is triggered by something in your personal data (like bookmark) another account might work for you as well.
