### ISSUE TITLE
Show the newest notification always on top

### ISSUE THREAD

**Issue by asdil12** [iNPUTmice/Conversations#1559]
When a new message is received, conversations views a notification.

```
msg 1
```

When another new message is received, it is appended to the notification:

```
msg 1
msg 2
```

This should be turned around:

```
msg 2
msg 1
```

so that the latest message is always visible.

Otherwise further msgs wouldn't be seen by the user when the visible text lines are exceeded.

**Comment by asdil1991** [comment]
+1

**Comment by pheerai** [comment]
:+1:

**Comment by tmolitor-stud-tu** [comment]
As far as I know this was the old behaviour but it was changed about 9 month ago.
Well, I think there should be an option in the (advanced) setting to let people choose which way they like their notifications.
@iNPUTmice would that be possible?
Some frieds of mine already complained they don't see what I wrote after the initial "hi".
So my friends don't know if I write something important (read: urgent) or not and I have no possibility to change that, because even writing "hello, please answer, it's urgent" wouldn't help as this message would not be displayed in the notification as well.
They would still see only the "hi" and think it's not urgent at all.

**Comment by xekon** [comment]
I am hoping for some options on the heads-up notification as well,
Like:
1. append Newest First
2. append Oldest First
3. New Notification per message.

https://github.com/siacs/Conversations/issues/3028

**Comment by xekon** [comment]
I am trying to make this change myself, but im not familiar with this code it looks to be in

    /src/main/java/eu/siacs/conversations/services/NotificationService.java

From what I can tell the notification is only sent when its the first message since your last reply, after that it calls a function buildMultipleConversation instead of sending a new notificationm, and it simply updates the text of the notification. Atleast thats how I think it works from examining the code over the last few hours.

This appears to be done in a For Loop within this buildMultipleConversation function. You could possibly change the direction of the For loop if you wanted to update the notification so that the last received reply is first? im not sure.

Also in this function I see "style.addLine(styledString);" That might be the part that actually adds new messages to the existing notification, but just speculating again.

I think to fix the problem with my watch I actually need a new Notification every time a user sends a message.... It is a little hard to tell what im doing without using a debugger or something, because I am not at all familiar with this code, and while the functions were thoughtfully named, I don't really see any comments in the code.

Any help is appreciate if anyone is more familiar with this, I am willing to spend more time and even incorporate this into some options if I can just figure out some basic stuff like how to make a new notification on every message.

**Comment by licaon-kter** [comment]
What do you show when the user wants to reply for that notification?

**Comment by xekon** [comment]
Im not sure, normally when i am going to reply to a notification I click on it which takes me to the conversations app.

I guess I need to figure out what is quickreply, and compare to how other applications handle this feature, and I totally get that conversations is NOT other applications and maybe there are sometimes reasons for doing things differently that in some or most cases is the better way.

because of my setup I really need to figure out a way to add an option to send a new notification on each received message so that my watch performs the same way as it does with other applications, so that I can clearly and easily read incoming messages from my watch.

**Comment by licaon-kter** [comment]
Quick reply adds your answer to the notification, you continue the conversation there, you don't dismiss it on reply. As Google wants.

**Comment by xekon** [comment]
Ah ok, I will need test that feature.

Just now I launched Google Hangouts on both my two devices.
Every time device 1 sends a message to device 2, device 2 sees that message notification on the lock screen for every received message.

but with conversations, you only see a notification for the first received message, this is the behavior I am trying to alter, are you saying that buildMultipleConversation is the wrong function to be altering?

Also I hope that I am explaining correctly the behavior I am trying to change. If you are not understanding the problem that I am trying to point out, I can place both phones on my desk and record them with a camera and throw that video on youtube to outline the problem that I am speaking of.
