### ISSUE TITLE
[Enhancement] Automatically file resend after connection lost 

### ISSUE THREAD

**Issue by thundergreen** [iNPUTmice/Conversations#1678]
As I'm using my phone a lot outside by crossing networks gaps all the time, it would be awesome if conversations would resend files automatically. This could be an option in advanced settings but very useful.

**Comment by singpolyma** [comment]
+1

**Comment by tmolitor-stud-tu** [comment]
That would be super cool!

**Comment by thundergreen** [comment]
Push push push...  Anyone working on this?

**Comment by tmolitor-stud-tu** [comment]
doesn't seem so :(

**Comment by thundergreen** [comment]
We need more people to vote for this feature.. Especially in mobile usage I
think it makes sense.. We have stream management and mam but what about
connection holes in a tunnel and u r just sending a text in a muc or a
file?

Thorsten Fröhlich
Am 26.06.2016 12:36 schrieb "tmolitor-stud-tu" <notifications@github.com>:

**Comment by emdete** [comment]
+1

there was a 'cancel' for sending images some releases ago and one could then 'resend' the image manually. now the 'cancel' is gone from the menu but a automatic resend won't take place either. this is very sad.

i think everything should be auto-(re)send once i espressed my wish to have that sent, no need to repeat myself ;)

**Comment by thundergreen** [comment]
No-one interested in this?  Nobody ever faces this issue at httpupload for example or messages in muc?  Me I face this at least 1 time a day

**Comment by tmolitor-stud-tu** [comment]
Me too. About 3 times a week.

**Comment by nightbluepn** [comment]
Is this issue still ongoing?
It happens too me all the time, i spent days trying to fix my server.
When Conversations showed 100% below the message i assumed the image got to the server and something else happened.
From other issues i gatherd that the 100% only refers to the outgoing buffer, if this is true than it's quite misleading anyway.

I too think it should be obvious for the messenger to not silently fail (sometimes the error shows after many more messages which all arrive, or minutes later when i closed the app), but to retry until the image is submitted.

@iNPUTmice if this issue is up to date and a higher bounty will get it done, please let me know.
