### ISSUE TITLE
UX: Joining conference after unknown error

### ISSUE THREAD

**Issue by SamWhited** [iNPUTmice/Conversations#1697]
Quite frequently I get the "Unknown error" snackbar when attempting to join the Prosody MUC. Generally I tap "Join" (or "Retry" or whatever it is), nothing happens, so I tap it again only for it to change into the "Unknown Conference" snackbar with the "Leave" button exactly where the "Join" button used to be, at which point I exit the conference.

I'm not sure what would be the best thing to do here; maybe keep the "Unknown error" snackbar in place until the join is complete (or fails again) and just hide the "Join" button to give the user an indication that something changed?

**Comment by iNPUTmice** [comment]
I know this issue is about the UX and that's totally fine and in fact I'm working on that. However I'd been interested in why you are getting an error presence from the prosody conference. Conversations will log the stanza in case of an 'unknown' error. Can you have a lock next time this happens? Maybe we can provide a better error message (or maybe avoid the error from happening at all.) Personally I'm not seeing the 'unknown conference / conference not found' error ever...

**Comment by iNPUTmice** [comment]
some of this has been addressed in a0d0ed34ae38f2377fdb3ad2c661b74b85f2df28

**Comment by SamWhited** [comment]
Yah, will do. I've tried to look a few times, but I normally don't notice it when it happens (which is why I haven't fixe it or filed an issue about that part of it); it does seem to happen more often with the Prosody conference than with anything else though.

**Comment by sokai** [comment]
Hi!
I will reference #1671 ([MUC] reconnect is not working) because it concerns the same behaviour/problem (often with Prosody, too).
Thanks for fixing this in advance.
