### ISSUE TITLE
Allow to delete selected messages from conversation

### ISSUE THREAD

**Issue by tomikmar** [iNPUTmice/Conversations#1748]
Conversation is almost perfect app, but one important feature is missing. Right now it is not possible
to delete a single/multiple selected messages from conversation (i.e. phone's internal storage).
I know that there is "Clear history", but here you need to remove everything.

A couple of real cases where it could be useful:
- I discussed something that is not important anymore and could be deleted. Right now I have huge history where important and not-important messages are mixed. I cannot just delete everything, because some of these things are still important for me.
- I sent password and it should be deleted just after it is used.

Two ideas how it could be implemented:
- Powerful one - Similar way to Cyanogen Mod SMS app where you can select multiple messages and perform group operation (e.g. delete, share). This way is very convenient and I often use it for clearing SMSes . 
  ![group-operations-example3](https://cloud.githubusercontent.com/assets/5788375/13553920/94537426-e399-11e5-8529-ed7e333e25f9.png)
- Simple one - just add one more option in "Message options"

```
----------------------------------
Message options 

Copy text
Delete message from local memory
----------------------------------
```

**Comment by lovetox** [comment]
problem is, only cause its deleted from your phone does not mean its deleted from the server, actually i dont know if you even can delete it from the server.

clear history only means that you dont fetch messages after a certain date. it does not mean the messages are not existent anymore on the server.

i skimmed through the MAM documentation and i found nothing about deleting messages.

**Comment by tomikmar** [comment]
I think that removing messages from my phone (without removing them from server) is good enough and it solves all my problems. 

Maybe there could be information to make it clear for all users, e.g.
```
You are going to remove message(s) only from this device. There can still
be other copies of the message(s) on server or other devices participating
in this conversation.

[ ] Don't show this message again.
```
On the other hand, messages are probably removed from server after some time (maybe after successful delivery?).

**Comment by horin** [comment]
I would also love to see this feature. It would be especially usefull in some cases. Lets say that my friend send me his password. I receive it, copy it somewhere else and then I want to delete this sensitive message. It could be implemented in dialog which shows when you long press message (right now only copy-text option is available there)

**Comment by jkufner** [comment]
This use-case makes sense. However there must be big fat warning, that the message is deleted only from this device and message archive on server. It may not be deleted from another devices not from sender/recipient devices. So it may be better if there is no such option.

**Comment by horin** [comment]
Well there should be a warning but Conversations is IMHO mainly used for encrypted communication. Talking about OTR or OMEMO it isnt a problem even if message is kept on server because it is encrypted. And it is up to counterpart to delete that message from their device if they think that it is sensitive. Implementing "all devices delete protocol" would be hard (not impossible), also probably not that much usefull and I would even say, in some cases, unwanted feature. Thats mainly because I, as a device owner, want to have control about messages on my device. Anyway I think that this feature is must have for good secure communication app

**Comment by jkufner** [comment]
> Conversations is IMHO mainly used for encrypted communication. 

No. Conversations is practicaly the only usable Jabber client for Android.

**Comment by bnvk** [comment]
Strongly agree with the desire and need for this feature. A per message delete ability is standard in almost every messaging client.

>  the message is deleted only from this device and message archive on server.

I am curious if this is true if `Server-side archiving preferences:` is set to `Never` in an accounts settings. 

> It may not be deleted from another devices not from sender/recipient devices. So it may be better if there is no such option.

I don't think "not be deleted from another devices" needs to be stated as *many* messaging tools (email, sms, etc...) this is understood. I highly disagree with the later- not to mention passwords, a user could have all sorts of messages they need to delete whereby deleting a whole thread would look suspicious. Not giving a user this choice as per some larger hypothetical risk of copies (of encrypted messages) on servers / other devices could be of grave risk to ones privacy and/or safety.

**Comment by tomikmar** [comment]
I strongly believe that I should have full control over my own device. I should decide what is deleted and what is kept. On the other hand, I wouldn't like to allow someone to remove something from my phone without my permission.

**Comment by bhavikmandalia** [comment]
any update on this ???

**Comment by kolAflash** [comment]
I'm having a situation where I could use this single/selected-message-deletion feature every few weeks.
This is just one scenario. But by the number of tickets opened for this, I'd guess not all but a respectful number of users have non-irrational use cases for this feature. (e.g. #50, #627, #1037, #1100, #1407)

---
My scenario:

Someone send me sensible data via XMPP+OMEMO (e.g. a password for something), and I want to delete those data from Conversations after copying it into a more secure place like a password store app (e.g. KeePass). So there will be an extra security barrier if someone manages to get my phone without having me activating the lockscreen first.

I'd neither like to delete the whole chat history. It's just too useful to lookup all the stuff we talked about before.
And I'd also not like to protect the whole Conversations app with an extra password (some Android versions offer that feature), because I'm willing to have much more time costly security measures for really sensible data (so that's what's the password store app is for), but really can't put an individual 20 characters password before everything because there might be a few sensible data somewhere inside it.

It's also not a problem for me, that this won't delete my chatpartners copy of the message. When receiving a message with sensible data I'm just responsible for securing that data on my device.
(and I'd only send sensible data to a chatpartner if I know he'd handle it safely)

Just put in a little text telling the user, that this won't delete his chatpartners copy of the message. So everything will be fine.

**Comment by 5a54a** [comment]
Someone did send me personal information and files (images) before using OMEMO. The link of the pictures is accessible by everybody (who knows the link). This person (new to xmpp) asks me to delete this message and pictures. Although I can delete this message and picture from my devices it seems impossible to also delete this picture from the server. XMPP is sometimes explained to persons new to xmpp as email for instant messages. Email can always be deleted from server. However, this is not the case for xmpp (with MAM). Showing to reload old deleted messages did not give any comfort at all for this user. 

Conclusion: for most (new) users not able to delete selected messages and files from server is totally unexpected behaviour and is hurting adopting new users to xmpp (as more private alternative to Whatsapp).

Friendly request: please consider an option to delete individual messages and files from server (in stead of storing this files/links forever).

**Comment by licaon-kter** [comment]
@5a54a For each account you can set up "Archive preference", that would take care of messages on the server side. Regarding files, it's a server thing, they should expire after a while (eg. One month), see the server info on their site, change the server to a better one.

**Comment by jakubmarciniak** [comment]
This feature would be very useful for me as well.

**Comment by tomikmar** [comment]
BTW. We have "Automatic message deletion" which is similar to functionality from this issue. I think both features would be useful.

**Comment by bhuvi8** [comment]
In 2018, it is still a nice feature to have. Currently long pressing on a message opens a menu with title 'Message options' with below options:
Share with...
Copy to clipboard
Quote
Correct message

Adding an option 'Delete message' which deletes the selected messages is a nice feature, and selecting multiple to delete once the delete is opened is an additional feature to have but that could be added as an enhancement on this delete message feature...

**Comment by harshitbansal05** [comment]
@iNPUTmice may I work on this?

**Comment by ditbl** [comment]
This missing feature hinders me at using conversations regularly. It would be very nice to have it similar to the delete feature in telegram. I don't need to delete on other people devices, but it would be good to have messages also deleted on my other device(s).

What is the reason that this feature is not needed by the developers?
I personally find it an essential one.
Do you delete all messages of a chat?
Or do you not mind, if you do not find any relevant old messages because they are hidden under thousands of irrelevant?

Nevertheless: Thank you very much for the great work!

**Comment by shubham2110** [comment]
Are we going to have this feature in near future ? 
Deleting Selected Messages from Local Chat.

**Comment by intika** [comment]
https://github.com/siacs/Conversations/pull/181, https://github.com/siacs/Conversations/pull/183 ??

**Comment by tomikmar** [comment]
I really miss this feature - it is essential for many people.

**Comment by danjde** [comment]
Hi Devs!
No any news about the ability to delete single chat specific contents (only from locale)?

Many thanks!

**Comment by CEHitchens** [comment]
Hello developers.

I would like to chime in. 
Next to use cases already described on this thread, I would like to add another:  Occasionally I will use XMPP&OMEMO messages to send something to myself. It could be URLs, passwords or even just reminders to have those available across several devices. Some I'd love to be able to delete whereas others I'd still like to keep.

Looking forward to future developments.

**Comment by asakura42** [comment]
Yep. Deleting messages is must have. Even if message deletes only on device.

**Comment by glavupak** [comment]
Why haven't you been able to make a feature that many users are asking for for 5 years?

**Comment by danjde** [comment]
Yes, it's really strange. I would be willing to support a fundraiser for this change...
