### ISSUE TITLE
Failed to connect with passwords containing special characters

### ISSUE THREAD

**Issue by ghost** [iNPUTmice/Conversations#1893]
#### General information
- **Version:1.12.8**
- **Device:HTC sensation XL**
- **Android Version:Android 4.0.3 stock**
- **Server name:openmailbox.org**
- **Conversations source:F-Droid**
  #### Steps to reproduce
1. Create account on any server with a password containing special characters
2. Connect to xmpp account from computer (psi)
3. Try to add account on Conversations
4. Enable account : it fails (unauthorized)
#### Expected result

It should connect!
#### Debug output

D/conversations(26182): app switched into background
D/conversations(27188): update unread count to 0
D/conversations(27188): restoring roster
D/conversations(27188): restoring messages
D/conversations(27188): restored all messages
D/conversations(27517): update unread count to 0
D/conversations(27517): restoring roster
D/conversations(27517): restoring messages
D/conversations(27517): app switched into foreground
D/conversations(27517): restored all messages
D/conversations(27517): app switched into background
D/conversations(27517): app switched into foreground
D/conversations(27517): maxime.alves@openmailbox.org: push mode false
D/conversations(27517): maxime.alves@openmailbox.org: connecting
D/conversations(27517): using dns server: 192.168.0.1 to look up openmailbox.org
D/conversations(27517): maxime.alves@openmailbox.org: using values from dns xmpp.openmailbox.org[62.4.1.33]:5222 tls: false
D/conversations(27517): maxime.alves@openmailbox.org: TLS connection established
D/conversations(27517): maxime.alves@openmailbox.org/phone: Authenticating with PLAIN
D/conversations(27517): maxime.alves@openmailbox.org: error connecting account. try again in 32s for the 2 time
D/conversations(27517): app switched into background
D/conversations(27582): update unread count to 0
D/conversations(27582): restoring roster
D/conversations(27582): maxime.alves@openmailbox.org: connecting
D/conversations(27582): restoring messages
D/conversations(27582): using dns server: 192.168.0.1 to look up openmailbox.org
D/conversations(27582): app switched into foreground
D/conversations(27582): restored all messages
D/conversations(27582): maxime.alves@openmailbox.org: using values from dns xmpp.openmailbox.org[62.4.1.33]:5222 tls: false
D/conversations(27582): maxime.alves@openmailbox.org: TLS connection established
D/conversations(27582): maxime.alves@openmailbox.org/phone: Authenticating with PLAIN
D/conversations(27582): maxime.alves@openmailbox.org: error connecting account. try again in 31s for the 2 time
D/conversations(27582): maxime.alves@openmailbox.org: error connecting account. try again in 27s for the 2 time
D/conversations(27582): maxime.alves@openmailbox.org: disconnecting force=false
D/conversations(27582): maxime.alves@openmailbox.org: waiting for tag writer to finish
D/conversations(27582): interrupted
D/conversations(27582): maxime.alves@openmailbox.org: error connecting account. try again in -34862s for the 1 time
D/conversations(27582): maxime.alves@openmailbox.org: connecting
D/conversations(27582): using dns server: 192.168.0.1 to look up openmailbox.org
D/conversations(27582): maxime.alves@openmailbox.org: using values from dns xmpp.openmailbox.org[62.4.1.33]:5222 tls: false
D/conversations(27582): maxime.alves@openmailbox.org: TLS connection established
D/conversations(27582): maxime.alves@openmailbox.org/phone: Authenticating with PLAIN
D/conversations(27582): maxime.alves@openmailbox.org: error connecting account. try again in 32s for the 2 time
D/conversations(27582): app switched into background

**Comment by iNPUTmice** [comment]
works for me. check your password

**Comment by mrPain89** [comment]
Hi, my girlfriend has the same problem with im.apinc.org ... But on my phone im.apinc.org works perfectly (her error is different, "account already exist"). I'll post an issue.

**Comment by mrPain89** [comment]
Tested behind a VPN and with antoher openmailbox address, still doesn't work. Which version do you use INPUTmice ?

**Comment by mrPain89** [comment]
So I can confirm this is a real issue, but it's not about the server but about the password containing special characters. Tested only with **openmailbox.org** and **im.apinc.org**. With a **conversations.im** account the password containing dashes and udnerscore works well. Don't know what is going on but when connecting via Psi on linux I got no  problems at all.

**Comment by iNPUTmice** [comment]
Without revealing your password: What kind of special character?

**Comment by PrivSecurity** [comment]
I have this issue too. I can log in on the web with this password but not in the Android app. To reproduce:

1. Tried to register with a very long password, about 100 characters containing all sorts of characters, like those you can auto generate from password managers, e.g.: 2ø'±s;ßà¼Å-Ñ¨é3Ó\Axé¡¬èáúÎ`|j"ÌÈÛ+ð³9ÝIsÎ'²ö?úg³&}kaÉa(òLÚ8¥Àò|»»¢¹WøùÝððÛyN$É*wÎÆ£ØÞzC´ö+>=¾®øúXÂìU

2. Conversations didn't support that many characters so I gradually choose shorter and shorter passwords until 30 characters were also too long. Then I just chose the auto generated default password of just 10 characters from the Conversations app. 10 characters is not a strong password these days and it is strange that a security oriented app like Conversations doesn't support long and strong passwords. The auto generated password this time was less strong than the first auto generated one from Conversations since I remembered at least some strange characters from the first one that I skipped since I wanted a long hard password from my password manager.

3. Now the registration worked fine but I then thought I should try and change the password to at least using those few 10 characters with very strange characters like in the 100 char password above. So I did and Conversations initially seemed to take it but then I suddenly got the message "Unauthorized" in red for that account. When I try to login from a web browser from my desktop the same password works fine but in the Android app it is still "Unauthorized" so I am rather stuck trying out Conversations with that account at least. I don't think I saw an option to change password from the web browser and it didn't really seem that I logged into a full Conversations application from the web but instead some just basic account settings and info page?

Without revealing my own password I believe at least one of the following 10 example 10 character passwords should be able to choose to reproduce the bug:

2ø'±s;ßà¼Å
-Ñ¨é3Ó\Axé
¡¬èáúÎ`|j"
ÌÈÛ+ð³9ÝIs
Î'²ö?úg³&}
kaÉa(òLÚ8¥
Àò|»»¢¹Wøù
ÝððÛyN$É*w
ÎÆ£ØÞzC´ö+
>=¾®øúXÂìU

There are rather many apps and services today that supports those kinds of password characters and also supports over 70 character passwords, some supports over 100 characters (Riot.im for example).

**Comment by iNPUTmice** [comment]
@PrivSecurity what server did you use? conversations.im?
