### ISSUE TITLE
Fails to resume session when using client certificates for auth

### ISSUE THREAD

**Issue by ThibG** [iNPUTmice/Conversations#2060]
#### General information
- **Version:** 1.14.5
- **Device:** Samsung Galaxy S3
- **Android Version:** CyanogenMod 13 (Android 6.0.1)
- **Server name:** self-hosted (sitedethib.com)
- **Server software:** prosody 0.10
- **Installed server modules:** Stream Managment, CSI, MAM, client certificates (mod_client_certs)
- **Conversations source:** F-Droid
#### Steps to reproduce
1. Connect to a server with stream management enabled, using a client certificate for authentication
2. Switch from wi-fi to mobile data
#### Expected result

Conversations should resume the XMPP session using Stream Management. However, it fails to do so, and will repeatedly fail connecting with a timeout every two minutes.
#### Debug output

```
10-06 20:33:37.080 13123 13123 D conversations: resetting all attempt counts
10-06 20:33:37.085 13123 13123 D conversations: thib@sitedethib.com: push mode=false listeners=false
10-06 20:33:37.105 13123 14702 D conversations: thib@sitedethib.com: connecting
10-06 20:33:37.110 13123 14702 D conversations: used lollipop variant to discover dns servers in 1 networks
10-06 20:33:37.110 13123 14702 D conversations: using dns server: 212.27.40.241 to look up sitedethib.com
10-06 20:33:38.065 13123 14702 D conversations: thib@sitedethib.com: using values from dns warp.sitedethib.com[[2001:910:1369:ffff:0:0:0:1]]:5222 tls: false
10-06 20:33:38.070 13123 14702 D conversations: thib@sitedethib.com: failed to connect to /2001:910:1369:ffff::1 (port 5222) after 15000ms: connect failed: ENETUNREACH (Network is unreachable)(java.net.ConnectException)
10-06 20:33:38.070 13123 14702 D conversations: thib@sitedethib.com: using values from dns warp.sitedethib.com[80.67.179.105]:5222 tls: false
10-06 20:35:08.260 13123 13123 D conversations: thib@sitedethib.com/0113bf7a-b2e7-4a68-b9a2-2421fb35e9aa: time out during connect reconnecting
10-06 20:35:08.300 13123 14751 D conversations: thib@sitedethib.com: connecting
```

On prosody's side, the corresponding debug output is:

```
Oct 06 20:33:40 socket  debug   server.lua: accepted new client connection from 37.160.65.213:57016 to 5222
Oct 06 20:33:40 c2sd14848   info    Client connected
Oct 06 20:33:40 c2sd14848   debug   Client sent opening <stream:stream> to sitedethib.com
Oct 06 20:33:40 c2sd14848   debug   Sent reply <stream:stream> to client
Oct 06 20:33:40 c2sd14848   debug   Received[c2s_unauthed]: <starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'>
Oct 06 20:33:40 socket  debug   server.lua: we need to do tls, but delaying until send buffer empty
Oct 06 20:33:40 c2sd14848   debug   TLS negotiation started for c2s_unauthed...
Oct 06 20:33:40 socket  debug   server.lua: attempting to start tls on tcp{client}: 0xe76ac8
Oct 06 20:35:11 socket  debug   server.lua: ssl handshake error: closed
Oct 06 20:35:11 c2sd14848   info    Client disconnected: ssl handshake error: closed
Oct 06 20:35:11 c2sd14848   debug   Destroying session for (unknown) ((unknown)@sitedethib.com): ssl handshake error: closed
Oct 06 20:35:11 socket  debug   server.lua: closed client handler and removed socket from list
Oct 06 20:35:11 socket  debug   server.lua: accepted new client connection from 37.160.65.213:57019 to 5222
Oct 06 20:35:11 c2s113e2d0  info    Client connected
Oct 06 20:35:11 c2s113e2d0  debug   Client sent opening <stream:stream> to sitedethib.com
Oct 06 20:35:11 c2s113e2d0  debug   Sent reply <stream:stream> to client
Oct 06 20:35:12 c2s113e2d0  debug   Received[c2s_unauthed]: <starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'>
Oct 06 20:35:12 socket  debug   server.lua: we need to do tls, but delaying until send buffer empty
Oct 06 20:35:12 c2s113e2d0  debug   TLS negotiation started for c2s_unauthed...
Oct 06 20:35:12 socket  debug   server.lua: attempting to start tls on tcp{client}: 0xcce428
```

**Comment by iNPUTmice** [comment]
You might want to report this to prosody as well. This doesn't seem to be a problem with stream management. Conversations doesn't even get to a point where it could try to resume a stream.

**Comment by ThibG** [comment]
Maybe, but disabling/re-enabling the account in Conversations is an effective workaround.

**Comment by iNPUTmice** [comment]
Get me a client certificate for your server and I can have a look

**Comment by iNPUTmice** [comment]
This seems like a server issue to me. Your argumentation is that by disabling the account Conversations resets itself in some way that will allow us to establish the TLS connection on the next try. You can debunk that theory by going into airplane mode while the account is connected. Disable the account. Reenable it. And then go out of airplane mode. If your theory would be correct Conversations should be able to connect right now. (Because it got reset during the disabling) But it won't be able to connect.

On the other side you have the stream close and the offline presence that is send during disabling the account while it is online which will reset the server. (The TLS session/state what ever)

Please report this to the Prosody developers.

**Comment by ThibG** [comment]
I'm still not entirely convinced:

1. Connect, switch airplane mode on and off: Conversations fail to reconnect
2. Connect, switch airplane mode on, disable account, switch airplane mode off, enable account: Conversation connects
3. Connect, switch airplane mode on, disable account, enable account, switch airplane mode off: Conversation fails to connect
4. Connect, switch airplane mode on, disable account, restart prosody, enable account, switch airplane mode off: Conversation still fails to connect
5. Disconnect, switch airplane mode on, enable account: Conversations fails to connect

So, it doesn't seem to have anything to do with resuming a session, but rather trying to establish a connection “too early”?

**Comment by iNPUTmice** [comment]
No it has nothing to do with resuming a session but with establishing a TLS
connection.

**Comment by Natureshadow** [comment]
Somehow, I started seeing similar behaviour even without using client certificates.

**Comment by iNPUTmice** [comment]
@Natureshadow if you have a bug to report please fill out the questionnaire (server version, client version, installed modules and so on) and if possible provide and adb logcat.

**Comment by rubensss18** [comment]
**General information**

Version: Conversations 1.18.3
Device: LG Nexus 5
Android Version: Android 6.0.1
Server software: Openfire 3.10.3
Installed server modules: HttpUploadComponent

**Steps to reproduce**

The same problem.
The client does not reconnect when the connection is lost. It stays on "connecting" and never connects.
However, if I disable and re-enable the account, the connection is established again.

This problem only happens when using a x509 certificate. If I don't use a x509 certificate the automatic reconnection is succesfull.

**Debug output (when reconnect fails)**

05-18 12:02:01.857 24605-24605 D: initializing database...
05-18 12:02:01.857 24605-24605 D: restoring accounts...
05-18 12:02:01.891 24605-24605 D: restoring conversations...
05-18 12:02:01.904 24605-24605 D: finished restoring conversations in 13ms
05-18 12:02:01.907 24605-24645 D: restoring roster...
05-18 12:02:01.907 24605-24605 D: update unread count to 0
05-18 12:02:01.913 24605-24605 D: schedule next idle ping
05-18 12:02:01.953 24605-24645 D: restoring messages...
05-18 12:02:01.965 24605-24650 D: ruben@mydomain.es: socket was null during force close
05-18 12:02:01.965 24605-24650 D: ruben@mydomain.es: connecting
05-18 12:02:01.980 24605-24605 D: start merging phone contacts with roster
05-18 12:02:01.980 24605-24605 D: finished merging phone contacts
05-18 12:02:01.981 24605-24650 D: used lollipop variant to discover dns servers in 1 networks
05-18 12:02:01.981 24605-24650 D: using dns server: 4.4.4.4 to look up mydomain.es
05-18 12:02:02.022 24605-24645 D: finished restoring messages in 69ms
05-18 12:02:06.464 24605-24767 D: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
05-18 12:02:06.498 24605-24767 I: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
05-18 12:02:06.500 24605-24767 I: Initialized EGL, version 1.4
05-18 12:02:06.538 24605-24605 D: app switched into foreground
05-18 12:02:06.979 24605-24771 D: target size overlay: 364.5 overlay bitmap size was 384
05-18 12:02:11.855 24605-24767 D: endAllStagingAnimators on 0x9df27580 (ListPopupWindow$DropDownListView) with handle 0x9dee6430
05-18 12:02:16.979 24605-24650 D: using dns server: 8.8.8.8 to look up mydomain.es
05-18 12:02:17.295 24605-24650 D: ruben@mydomain.es: using values from dns mydomain.es[MY_IP]:5222 tls: false
05-18 12:02:41.613 24605-24605 D: app switched into background
05-18 12:02:44.806 24605-24605 D: app switched into foreground
05-18 12:03:33.900 24605-24605 D: ruben@mydomain.es/phone: time out during connect reconnecting (secondsSinceLast=91)
05-18 12:03:33.904 24605-26261 D: ruben@mydomain.es: connecting
05-18 12:03:33.906 24605-26261 D: used lollipop variant to discover dns servers in 1 networks
05-18 12:03:33.906 24605-26261 D: using dns server: 4.4.4.4 to look up mydomain.es
05-18 12:03:48.899 24605-26261 D: using dns server: 8.8.8.8 to look up mydomain.es
05-18 12:03:49.054 24605-26261 D: ruben@mydomain.es: using values from dns mydomain.es[MY_IP]:5222 tls: false
05-18 12:03:59.454 24605-24605 D: app switched into background
05-18 12:05:04.970 24605-24605 D: ruben@mydomain.es/phone: time out during connect reconnecting (secondsSinceLast=91)
05-18 12:05:04.977 24605-27661 D: ruben@mydomain.es: connecting
05-18 12:05:04.980 24605-27661 D: used lollipop variant to discover dns servers in 1 networks
05-18 12:05:04.981 24605-27661 D: using dns server: 4.4.4.4 to look up mydomain.es
05-18 12:05:19.979 24605-27661 D: using dns server: 8.8.8.8 to look up mydomain.es
05-18 12:05:35.084 24605-27661 D: ignoring timeout exception when querying AAAA record on 8.8.8.8
05-18 12:05:35.086 24605-27661 D: ruben@mydomain.es: using values from dns mydomain.es[MY_IP]:5222 tls: false
05-18 12:06:36.004 24605-24605 D: ruben@mydomain.es/phone: time out during connect reconnecting (secondsSinceLast=91)
05-18 12:06:36.017 24605-28918 D: ruben@mydomain.es: connecting
05-18 12:06:36.027 24605-28918 D: used lollipop variant to discover dns servers in 1 networks
05-18 12:06:36.028 24605-28918 D: using dns server: 4.4.4.4 to look up mydomain.es
05-18 12:06:51.030 24605-28918 D: using dns server: 8.8.8.8 to look up mydomain.es
05-18 12:06:51.214 24605-28918 D: ruben@mydomain.es: using values from dns mydomain.es[MY_IP]:5222 tls: false


**Debug output (when disable and enable account reconnect succesful)**


**-- DISABLE ACCOUNT**

05-18 12:10:23.320 24605-32233 D: ruben@mydomain.es: sending offline presence
05-18 12:10:23.322 24605-32233 D: ruben@mydomain.es: disconnecting force=false
05-18 12:10:23.322 24605-32233 D: ruben@mydomain.es: waiting for tag writer to finish
05-18 12:10:23.322 24605-32233 D: ruben@mydomain.es: sleep interrupted
05-18 12:10:23.522 24605-32233 D: ruben@mydomain.es: tag writer has finished
05-18 12:10:23.522 24605-32233 D: ruben@mydomain.es: closing stream
 
**-- ENABLE ACCOUNT** 
                                --------- beginning of system
05-18 12:10:24.902 24605-32259 D: ruben@mydomain.es: connecting
05-18 12:10:24.903 24605-32259 D: used lollipop variant to discover dns servers in 1 networks
05-18 12:10:24.904 24605-32259 D: using dns server: 4.4.4.4 to look up mydomain.es
05-18 12:10:39.899 24605-32259 D: using dns server: 8.8.8.8 to look up mydomain.es
05-18 12:10:40.183 24605-32259 D: ruben@mydomain.es: using values from dns mydomain.es[MY_IP]:5222 tls: false
05-18 12:10:40.457 24605-32259 D: getting certificate chain
05-18 12:10:40.669 24605-32259 D: searching for mydomain.es in srvNames: [] xmppAddrs: [*.mydomain.es] domains:[]
05-18 12:10:40.674 24605-32259 D: ruben@mydomain.es: TLS connection established
05-18 12:10:40.745 24605-32259 D: ruben@mydomain.es/phone: Authenticating with EXTERNAL
05-18 12:10:41.037 24605-32259 D: ruben@mydomain.es: logged in
05-18 12:10:41.133 24605-32259 D: ruben@mydomain.es: starting service discovery
05-18 12:10:41.133 24605-32259 D: ruben@mydomain.es: do not wait for service discovery
05-18 12:10:41.165 24605-32259 D: ruben@mydomain.es: online with resource phone
05-18 12:10:41.166 24605-32259 D: ruben@mydomain.es: fetching roster
05-18 12:10:41.385 24605-32259 D: ruben@mydomain.es: successfully enabled carbons
05-18 12:10:41.395 24605-32259 D: AxolotlService : Couldn't find <item> in bundle IQ packet: <iq to="ruben@mydomain.es/phone" from="ruben@mydomain.es" xmlns="jabber:client" id="4ktsvc8rwf" type="result"><pubsub xmlns="http://jabber.org/protocol/pubsub"><items node="com.tecnobit.scipconversations.axolotl.bundles:96802103" xmlns="http://jabber.org/protocol/pubsub"/></pubsub></iq>
05-18 12:10:41.397 24605-32259 W: AxolotlService (ruben@mydomain.es): Received invalid bundle:<iq to="ruben@mydomain.es/phone" from="ruben@mydomain.es" xmlns="jabber:client" id="4ktsvc8rwf" type="result"><pubsub xmlns="http://jabber.org/protocol/pubsub"><items node="com.tecnobit.scipconversations.axolotl.bundles:96802103" xmlns="http://jabber.org/protocol/pubsub"/></pubsub></iq>
05-18 12:10:41.400 24605-32259 W: AxolotlService (ruben@mydomain.es): Received invalid prekeys:<iq to="ruben@mydomain.es/phone" from="ruben@mydomain.es" xmlns="jabber:client" id="4ktsvc8rwf" type="result"><pubsub xmlns="http://jabber.org/protocol/pubsub"><items node="com.tecnobit.scipconversations.axolotl.bundles:96802103" xmlns="http://jabber.org/protocol/pubsub"/></pubsub></iq>
05-18 12:10:41.401 24605-32259 I: AxolotlService (ruben@mydomain.es): Adding own IdentityKey org.whispersystems.libaxolotl.IdentityKey@8035d0c1 to PEP.
05-18 12:10:41.403 24605-32259 I: AxolotlService (ruben@mydomain.es): Adding new signedPreKey with ID 6 to PEP.

**Comment by iNPUTmice** [comment]
@rubensss18 get me a client cert for that server and I might have time to take a look.

**Comment by rubensss18** [comment]
This is my client cert:

`-----BEGIN CERTIFICATE-----
MIIDojCCAoqgAwIBAgIBCzANBgkqhkiG9w0BAQUFADBDMREwDwYDVQQKEwh0ZWNu
b2JpdDERMA8GA1UECxMIdGVjbm9iaXQxGzAZBgNVBAMTEnRtc3RlYy50ZWNub2Jp
dC5lczAeFw0xNzA1MTgxMDU3MDBaFw0xODAzMjIwOTU3MDBaMF8xCzAJBgNVBAgT
AmVzMQ4wDAYDVQQKEwVydWJlbjEOMAwGA1UECxMFcnViZW4xDjAMBgNVBAMTBXJ1
YmVuMSAwHgYJKoZIhvcNAQkBFhFydWJlbkBteWRvbWFpbi5lczCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAO5qfdpR+XKL1/ec41MOJPSlrVRC6TU+ZRVy
B133h92tmlF3HvU/nyN+G5SNURXyVAQtieDMr0Y+lnDzga+7Z65yKk5SzUl2h8dj
x9TDzl2svM5OhnvESJd5m79PLtWM2JuGeE3Ukht+dcS/Nd16aXpZqaOh09m3tR6O
X9Jbt2j+zSiVxQr7SFmaMQOB9kBPtv+mnhJBInEMb6V+e/wuvxhTFpo5WvcuEqea
j47AwEQgL+//2zjD1CZZkxy8w2g6aCB53qUaFJ6hrEThrHbF6IOxSX4wLrjnc/oT
y7sjeSTAIDveAGkl5tzpCOX2VCozqcCpBySaG751N9RUoEf6vZ8CAwEAAaOBhDCB
gTAJBgNVHRMEAjAAMB0GA1UdDgQWBBR8RwCIaQ7kdZH7eCJL0L2VAdFWhDBVBgNV
HSMETjBMoUekRTBDMREwDwYDVQQKEwh0ZWNub2JpdDERMA8GA1UECxMIdGVjbm9i
aXQxGzAZBgNVBAMTEnRtc3RlYy50ZWNub2JpdC5lc4IBATANBgkqhkiG9w0BAQUF
AAOCAQEAG5OPTjkC1q5SQSXpXLAQPaFEX9P0Wcr514mdlkP1ogs4Kr4HpLNVHvV7
btJ+RDOjDV10tjRvNO2wzyjYCaPkELqzhZv3gNlsP8YSSZVlD9aX3YMDaiiyoFDR
Cao0ZnSLZnVuqB9jaYwmXmT1BBKTphmiUHk/cQUw7eDql6LVct+Tbb8t/wtXiAFA
ANDRbmB4CONHMRMohf7BtSNsdrBXtNX6zaJWcUN+QfFgfN8TAOqcYHAEwUJg04ab
Zk28jAvJmdNAKpepUGj3WIVeheqm9KawlGKNM4ulcbm8DWf6YhjD6B36CGYb3dNx
X+4P9e7B8VwBfK/EVQ+Ru+jsKK/DYQ==
-----END CERTIFICATE-----`


If you need anything else do not hesitate to ask me.

regards

**Comment by iNPUTmice** [comment]
@rubensss18 I meant the key+cert (=the PKCS file) so I can login to the server. Sorry for not being clear about that.

**Comment by rubensss18** [comment]
I atach my PKCS file but you can't login to the server because it's  a private server in a private VPN and the public DNS's can't resolve the private domain. 
The server is a normal openfire version 3.10.3.

**Comment by iNPUTmice** [comment]
> you can't login to the server because it's a private server in a private VPN and the public DNS's can't resolve the private domain.

Ok. I'm sorry I can't help you then.

**Comment by rubensss18** [comment]
ok, thank you.
