### ISSUE TITLE
Add expert setting to disable "unable to connect" notification entirely

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [iNPUTmice/Conversations#2126]
Please add an expert setting to deactivate those error notifications entirely.

Some of my friends are rather annoyed by this and told me they want to uninstall Conversations because of those notifications.
Those are happening quite often for them because of slow/bad wifi connections.

(related: https://github.com/siacs/Conversations/issues/1815 )

**Comment by iNPUTmice** [comment]
Please provide reasons for why Conversations is failing to connect. (Blocked port, timeout). I much rather fix the actual problem (by increasing the timeout for example) then provide a way to hide the problem. (I told you that in the other issue as well.)

**Comment by tmolitor-stud-tu** [comment]
Well, I think it is a timeout issue but it could be a blocked port, too.
One of my friends told me that there is a "poor wifi connection" when the notification appears (suggesting a timeout issue).

But even if you increase the timeout this wouldn't fix all cases of "poor wifi connections" or even affect other people: at least timeouts are there for a reason and too high timeouts can cause trouble, too.

I really understand why you want to fix the actual problem, but in my opinion this is not always possible (blocked ports for example) and providing an expert knob to turn out those notifications for people that frequently operate under such hostile environments would help a lot in this situation.

**Comment by iNPUTmice** [comment]
> but in my opinion this is not always possible (blocked ports for example) 

You can run your XMPP in direct TLS mode on port 443. I have yet to encounter a wifi that is not 'tricked' by that.

**Comment by mimi89999** [comment]
I know one Wi-Fi, that blocks DNS traffic to other servers than their and their DNS is very restrictive... In that case XMPP on 443 won't help...

**Comment by tmolitor-stud-tu** [comment]
yes, mimi89999 is right: you cannot solve every connection problem...
And not everybody can activate direct TLS mode on port 443 on their servers to work around connectivity issues (I for example can not).

**Comment by iNPUTmice** [comment]
> I know one Wi-Fi, that blocks DNS traffic to other servers than their and their DNS is very restrictive... In that case XMPP on 443 won't help...

The begs the question on why you would even log on to that wifi. If it's that restrictive WhatsApp/Google Play Services might not work either.

> And not everybody can activate direct TLS mode on port 443 on their servers to work around connectivity issues (I for example can not).

Why not? You can easily run HTTP and XMPP on the same port. This quite honestly what bugs me the most about these kind of feature requests. They smell like lazy system administrators why try to pass on the responsibility to the client.

**Comment by tmolitor-stud-tu** [comment]
It's not that I'm lazy but I have already port multiplexing configured for openvpn and apache on port 443 (which btw. runs somewhat instable for SVN requests).
If you can point me to some good port multiplexer capable of multiplexing openvpn, https and xmpps, I'll give it a try.
But I really don't want to make my multiplexing system even more unstable (hence my statement that I cannot run xmpp on port 443)

I don't know how restricted my/that wifi really is because I don't have access to that wifi but it seems that whatsapp is working over this wifi.

**Comment by iNPUTmice** [comment]
Try [sslh](http://www.rutschle.net/tech/sslh.shtml) Multiplexing happens on TLS level (with ALPN and SNI) and not by 'guessing' the content. (Although sslh has also the abiltiy to guess). You need the latest version though. The sslh patch was written by the same person who implemented ALPN support in Conversations so it should work pretty fine. If not I'm sure you can hit him up on the Conversations MUC.

**Comment by tmolitor-stud-tu** [comment]
Okay, I've configured this, I hope it will run stable.
Now the last question: does conversations do a fallback to the xmpps srv record if those are provided?
Example:
    _xmpp-client._tcp.example.org. 3600 IN SRV 10 0 5222 xmpp.example.org.
    _xmpps-client._tcp.example.org. 3600 IN SRV 20 0 443 xmpp.example.org

**Comment by iNPUTmice** [comment]
@tmolitor-stud-tu all SRV records are tried. You can set priority to control what is tried first if I remember correctly. Actually (as long as your sslh setup works stable) you might want to prefer xmpps because it saves you a roundtrip time (which can also count towards potential timeout problems.) We prefer it on conversations.im

You might want to check with adb just to be sure though.

**Comment by lazyadmin111** [comment]
Hey folks,

I think the the fundamental problem behind that wish for that feature is a social one. But so far, I think, the developers see in it only the technical side of the problem. I don't want to say that it is helpful to solve the technical problems concerning disconnects to the server, that's all quite fine. However, there will always be circumstances where there will be no connection, be it whatever. 

The more serious problem is the following social one: I and I suppose many other fans of Conversations install it to as many friends as possible, and most of them are no computer nerds. They comply to install it besides their beloved whatsapp, but not that joyful and happily, e.g., because they don't comprehend what the privacy stuff is all about. 

Furthermore, they are all used to whatsapp, that's their idol, and this whatsapp doesn't complain about connection troubles. So if that "nasty" Conversations complaines about some connection problems to a server -- for whatever reasonable reason -- they just see that their favored whatsapp which they use with many friends doesn't complain and annoy them, and this Conversations app which they use only with 1 or 2 friends shows them some trouble.

Therefore, it would be helpful to disable connection problems at all in the expert settings, if I or people like me install -- after long hours of persuasion -- your app on the phone of one more of ours friends. For many people this option might not be what they are wishing, they might want to be informed about each little connection problem, but for some friends this would be a great help definitely.

greets & nice wishes for the new year

**Comment by tmolitor-stud-tu** [comment]
@lazyadmin111 Yes, that's **exactly** the problem I ran into. And there is virtually no way to convince her to install the app again :(

And I fear I will have this problem with other friends, too, once their connectivity changes (for whatever reason).

**Comment by BlauerHunger** [comment]
This problem is caused by the lazyness they were taught by WhatsApp etc. 
Most app developers see things from a technical point of view. This is the reason why K9-Mail lacks a modern UI, Conversations doesn't have stickers or audio/video calling ...

I think the expert setting you are asking for should be "be more quiet" (or "Luser Mode") which disables connection error messages, automatically resends failed messages and media, hides the fingerprints, enables last seen, status etc. (=configures Conversations to be more WhatsApp-like)

**Comment by licaon-kter** [comment]
I do agree that's annoying, but, consider this, Conversations never works (be it bad connection, blocked server, bad Doze settings, something) but it does not say anything, how long does a user still use it then?

Get Ring or Antox, test them between 2 devices, they never worked for me, I only got like 2 messages sent in one week(!!!!), and I cared, [I wanted them to work](https://github.com/Antox/Antox/issues/created_by/licaon-kter), but nothing helped, I gave up.

**Comment by tmolitor-stud-tu** [comment]
@licaon-kter The thing is: If I set the "be quiet about connection problems"-setting for my non tech-savvy friends I would carefully monitor if the app still works for them and if not I could always deactivate the setting to get a better knowledge of what exactly is failing (and when etc.).

Or the other way round: I could selectively activate this "be quiet"-setting if one of my friends is annoyed by this and leave it off for all other friends.

But not having this (expert) setting at all leaves me...well...without options.

**Comment by licaon-kter** [comment]
Again, so why not go the other way... don't monitor anything, if an user sees the notification THEN fix their issue. Your scenario sounds strange, many things could go wrong (connection, sync, certificates, app closed, foreground service, etc) that might not signal either your side or theirs that it's not actually working.

**Comment by tmolitor-stud-tu** [comment]
@licaon-kter _Please read what @lazyadmin111 wrote. He is 100% right and I already lost a friend using Conversations for exactly the reasons he pointed out._

This is not something technical, because you cannot technically make sure that one **never** has connectivity issues. But you can make sure that one isn't annoyed by occasionally occuring connectivity issues _one wouldn't even notice if they weren't announced so prominently via notification_.

**The argument, that problems would go unnoticed this way, doesn't hold water, because:**

1. I wouldn't activate this **expert** setting for friends not annoyed by those notifications
2. Connectivity issues only occuring temporarily and occasionally will be ignored by my friends. If they are announced via notification or not doesn't even matter here.
3. Connectivity issues present for a longer time will eventually be noticed by my friends or myself and we would take appropriate actions then (regardless of this notification).

I admit, that with point 3 there is a difference between tech-savvy users and non tech-savvy ones. Tech-savvy users (like me) mostly want to be immediately informed about connectivity issues as opposed to non tech-savvy users that tend to be annoyed by such notifications (as @lazyadmin111 pointed out).

It would be absolutely enough for such (easily annoyed) people, if Conversations tried to reconnect in the background periodically.

**Comment by BlauerHunger** [comment]
@licaon-kter wrote:
> Not sure how you'd check if it works for them, phone them? Use Whatsapp to asked them if they got your Conversations message?

@tmolitor-stud-tu didn't want the information below a message to get removed, just the error notifications. If a message delivery fails, you get a red text below it. Additionally, you can enable delivery notifications in expert settings (=double tick from WhatsApp). 
There are ways to find out whether the message was delivered or not, without notifications which annoy non tech-savy users.

**Comment by licaon-kter** [comment]
@BlauerHunger Yes, that's a way, again, it depends on the problem, you see that when you want to send a message, but you don't see anything if you don't open the app (having the app running in the background and the error notification disabled that is), you don't see anything wrong even if you open the chat.

Keep in mind that no message means 2 things:
* no message because no one said anything
* there is an error

I find the notification annoying too, but that signals there is something wrong with the app or the internet that needs fixing, what's wore annoying then, a notification that you can swipe away or a chat app that does not get any messages for you.

What do Whatsapp users do when they can't connect (and they're not announced)?

**Comment by tmolitor-stud-tu** [comment]
@licaon-kter WhatsApp users see there is no blue tick displayed for their messages and anticipate that there could be an issue with their phone (especially if this happens for more than one contact). The reaction varies but usually involves turning on/off wifi or restarting their phones.

**Comment by tmolitor-stud-tu** [comment]
@iNPUTmice Please see https://github.com/siacs/Conversations/issues/2126#issuecomment-269309136 and my last comment

**Comment by haxwithaxe** [comment]
having a notification in the notifications stack is annoying. having a message in the app when something recoverable or transient goes wrong would prevent excess android notifications and still surface problems to the user.
i propose that android notifications be used for app errors, authentication errors, and select (preferably fatal) protocol errors. Once a configuration has been verified to work, failure to connect to a sever for anything but authentication or crypto errors is probably transient and doesn't need to sound an alarm by raising an android notification.
having an in app message with something like "This account has failed to connect 11 times in the last 36hrs. See this link for information on potential causes and troubleshooting." would be far more useful and much more appropriate for the level of concern that error causes.

**Comment by licaon-kter** [comment]
@haxwithaxe So your ROM will aggressively kill Conversations if you disable 'foreground service' in Conversations->Expert settings ?

**Comment by haxwithaxe** [comment]
i'm using stock 7.1.1 on my nexus6. it doesn't seem to kill it. i reenabled
that setting just before i posted that message so it's too early to tell if
it's changed the behavior probably. i don't think that is entirely the
problem (if at all) though. k-9 mail also has failures to connect at the
same times. my home wifi has periodic performance issues so it's probably
being triggered by that.

**Comment by licaon-kter** [comment]
nvm, I've mixed up the issues.

**Comment by rajeevn1** [comment]
i) @iNPUTmice I agree that we should fix the root cause, but sometimes the root cause is outside ourcontrol.  I would like to disable 'unable to connect' notification because when I am travelling and am in a region with unreliable mobile data connection I get this alert often.  Only way for me to disable it is to disable all accounts, and then remember to enable the accounts when I have good mobile data coverage.

ii) I also get this message when I am running conversations in "battery optimized" background mode with push notifications. This may be a bug in Conversations.

**Comment by lazyadmin111** [comment]
Is it harder to add this option as I can imagine?

**Comment by vvug** [comment]
It is not possible to fix the "root cause" of this problem, as sometimes there's just no connectivity. The annoyance of that message could be less if Conversations could dismiss it automatically when connectivity is back. But still, it's not worth having it. At most: just add an indicator, within the app, that shows if Conversations is connected to the server.

**Comment by licaon-kter** [comment]
There's a difference between "no actual connectivity" and "Android says there is connectivity but no packets are sent/received".

Conversations can't really discern between "bad network" and "server is down", I for one would like to know it's not actually connected to the server, instead of just thinking/hoping messages might be sent when the server recovers, in 1 hour/day/whatever.

**Comment by d9h20f** [comment]
As others indicated, that sort of information could and should really be displayed inside the application. It's nowhere near important enough to warrant interrupting any other activity to inform you that your train is going through a tunnel. The amount of times your server will ever be down or the router will be misconfigured is nothing compared to the amount of times your phone goes 'ding' because of a temporary connection loss, and even then it doesn't actually matter. @vvug described the problem pretty well in #2640.

The notification is (very marginally) useful to help solve connection problems. The thing is, regular users don't solve connection problems, and they definitely don't send bug reports with accurate descriptions of their situation and how it's failing to connect. @lazyadmin111 and @BlauerHunger are right, this is a technical setting, not one made for users.

**Comment by licaon-kter** [comment]
> this is a technical setting, not one made for users

And their friends will show them how to enable it, then complain that "the app does not work", when the problem is elsewhere. IMHO, that's the reason it was not yet implemented.

**Comment by tmolitor-stud-tu** [comment]
@d9h20f is right, and my users constantly complain about those notifications.

@licaon-kter Nobody talked about just displaying nothing. A toast inside the app like it's done for disabled accounts would be enough. This way nobody is bothered by spurious notifications but nevertheless is informed what's going on when he opens the app.

**Comment by licaon-kter** [comment]
@tmolitor-stud-tu Why are they seeing it often enough to complain?
I rarely saw one, and that was when the server operator did some upgrades or moved servers, like once per month at most. And yes, I roam between mobile and Wi-Fi during the day.

**Comment by tmolitor-stud-tu** [comment]
@licaon-kter Bad wifi/mobile connectivity for example: the phone is connected but internet access is very slow or not working at all.

Like @vvug said: You can not fix all root causes of this, but non-technical people don't want to know their phone is temporarily not connected. If the want to know if a message is sent, they open conversations and see if the message's state is still "sending" or "waiting" or whatever.
Or they would see the toast that conversations isn't connected at the moment, if this was implemented.
_This is exactly what users are already used to because other messengers like WhatsApp do the same (they don't show a "unable to connect" notification but you can see if a message was correctly sent or not if you open the messenger)._

Power users like you @licaon-kter can enable the notifications to be informed as usual, but that's something not wanted by non-geek users at all.

To make it clear: I'm voting for a expert setting to disable the notification which would display a toast inside the chat like it is already done for disabled accounts.
This would suit everyone. Power users can leave the notification enabled and others can just disable them if they get annoyed by them. A win-win for everybody.

**Comment by d9h20f** [comment]
If anything, I think the expert setting should be to enable the notification. Anything that can be annoying should be opt-in, not opt-out. A thin red bar inside the application with a message like "You don't seem to have access to the internet right now, please check your connection settings. Your messages will be sent when you go back online." should be more than enough.

Server problems are not the issue here (although: you can't do anything to fix those, so there's no need to be constantly notified about it), unstable connections are (and you don't need to be notified about that either, because you can already tell by everything else on your phone refusing to connect and the network indicator going blank). Not all places are equally well equipped with network masts.

**Comment by licaon-kter** [comment]
> "You don't seem to have access to the internet right now, please check your connection settings...."

I don't get any notification when there is no actual connection, eg. Wi-Fi and mobile data turned off. This is not the issue here.

> Server problems are not the issue here (although: you can't do anything to fix those, so there's no need to be constantly notified about it),

They can be, and yes you can do something: [choose another server](https://gultsch.de/compliance_ranked.html), one that works [most of the time](https://status.conversations.im/historical/).

> unstable connections are

Yes, these indeed, when Android lies that there is a connection while actually just trying to connect.

**Comment by d9h20f** [comment]
Are you being intentionally obtuse?

**Comment by licaon-kter** [comment]
No, but I've answered too often here indeed. Cheers

**Comment by annafallasktick** [comment]
Can ui solutions be distilled to: 

* fewer toasts (zero floor option)
* change toast semantics (message delays in lieu of connectivity problems)
* preference for in-app delivery disposition symbols

**Comment by annafallasktick** [comment]
* disable notifacation with sunset (can only be disabled N hours or X days, then reverts to enabled)

** disable iteratively via Tasker (power users managing sheeple devices)

* redirect notification output [from ui to ..]

**Comment by lazyadmin111** [comment]
@tmolitor-stud-tu @mimi89999 @BlauerHunger @licaon-kter @d9h20f @annafallasktick @vvug ...:
I don't why inputmice didn't fix this annoying message so long, but maybe we can together bountysource this and thus make it attractive for him to fix this. Adding this option shouldn't be too much work and if we put some bucks together he won't hesitate to add it!

What you think about it?

**Comment by whitetornado** [comment]
in for it, tell me what i shall deposit??

2017-10-28 18:09 GMT+02:00 lazyadmin111 <notifications@github.com>:

**Comment by lazyadmin111** [comment]
@whitetornado 
I would happily give my 10€ for this, and hope the others here join me!

**Comment by tmolitor-stud-tu** [comment]
@lazyadmin111 @whitetornado I guess this will never be resolved, but maybe this helps you:
https://github.com/siacs/Conversations/issues/1879#issuecomment-348525593

**Comment by licaon-kter** [comment]
Fixed for Oreo and later, only.
