### ISSUE TITLE
Hide received messages in notification bar

### ISSUE THREAD

**Issue by peperunas** [iNPUTmice/Conversations#265]
Is possible to implement this feature? It bugs me a lot that every message is shown every time that I open my notification bar. They could be grouped by sender like: "Sender: X new messages.". Thanks!

**Comment by xavihernandez** [comment]
Sorry forduplicate @iNPUTmice.

Well I think the best implementation is to let the user decide wether to show sender and message, sender without message or hide both.

As far as i'm concerned I think it is a privacy matter, and since it is not at System level, all applications displaying "sensitive" content should implement private notificaitons.

**Comment by contriba1** [comment]
Would #2726 be a step toward implementing this feature?

Agree with @xavihernandez, this would defend against shoulder-surfing since we could hide notification content even when the device is **un**locked. (Android 10 only allows hiding it when the device is locked.) A second checkbox could additionally allow hiding the sender's avatar in the notification. I would like to use Conversations exclusively, but this feature is currently preventing me from switching. Thanks for the consideration.

**Comment by licaon-kter** [comment]
Disable "heads-up notifications" in either notifications settings for the on Android and later or in Android settings on Android 6 or later.

**Comment by iNPUTmice** [comment]
Android can now do this natively.

**Comment by contriba1** [comment]
Thanks for the tips. To clarify, when a chat comes in I _would_ like to see a notification banner (heads-up notification) that says something generic like "1 message from 1 contact" or "Message(s) received."

> Android can now do this natively.

@iNPUTmice I don't see this in the Android notification settings; can you share the name of the option? It is easy to hide the notification content on the **lock** screen using Android 10's native settings, but it is not possible natively to hide the content when the device is **unlocked** (while still showing a generic banner, as described above). The options that Android 10 offers are to 1) show all notification content, 2) hide sensitive content on the lock screen.

Also, in regards to approaching this through Android settings, I currently see no built-in way to granularly limit hiding of notification contents for specific apps. The closest option is to disable notifications altogether, which would not be equivalent.

> Disable "heads-up notifications" in either notifications settings for the app on Android and later or in Android Settings on Android 6 or later.

@licaon-kter I unchecked Heads-Up Notifications on one device, but the notifications still show the message content and sender avatar. Other device does not have this option, but unfortunately this wouldn't be a solution either way because it would result in no banner.
