### ISSUE TITLE
(Feature request) Multiple selection of text

### ISSUE THREAD

**Issue by abbradar** [iNPUTmice/Conversations#2659]
#### General information

* **Version:** 1.21.0
* **Device:** Xiaomi Mi5s
* **Android Version:** LineageOS 14.1
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Attempt to select several "blocks" (one or several adjastent messages) of text at once.

#### Expected result

Block can be selected and copied (ideally can be selected partially, like plain text -- e.g. a block and a half), result will be a chat log:

```
aaa: foo
bbb: bar
aaa: baz
```

EDIT: To clarify: by "mulitple selection" I don't mean actual multiple selection like in some text editors -- rather I mean selection of continuous text between blocks.

#### Actual result

One can only select text from one block.

**Comment by l-jonas** [comment]
@abbradar It isn't possible to select text in the current version, only to copy the whole message to the clipboard.

**Comment by abbradar** [comment]
@l-jonas I understand, that's why it's a "feature request".

**Comment by l-jonas** [comment]
@abbradar This was a reference to your "Actual result". It sounded like it is/ was possible to select parts of one block.

To the feature request: It's very complicated to implement partially selecting due to the underlying ListView with multiple (wrapped) TextViews. Selecting of multiple blocks is technically easily possible (and e.g. implemented in (bad example) WhatsApp). However, I'm not sure if it's a good idea to implement this now because the old ListView is used instead of the new RecyclerView which was introduced with Android 5.
