### ISSUE TITLE
No autojoin mucs when muc server its restarted

### ISSUE THREAD

**Issue by srgcdev** [iNPUTmice/Conversations#2690]
#### General information

* **Version:**  1.21.0
* **Device:** Nexus 5x
* **Android Version:** Android 6.0 Stock or Android 7.1 LineageOS
* **Server name:** self hosted
* **Server software:** ejabberd 17.09
* **Installed server modules:** Stream Managment, CSI, MAM...
* **Conversations source:** F-Droid

#### Steps to reproduce

1. A contact in server different that muc server, eg suchat.org, joins a muc on my self hosted server
2. I restart my server
3. This contact form suchat.org dosen't autojoin again to the muc and he has to leave the room and enter again or logout and then login his account on conversations

#### Expected result
The contact is autojoined again after I restart my self hosted server

Thanks.

**Comment by mw80** [comment]
Had the same issue. Resolved by using module group_bookmarks

**Comment by sokai** [comment]
May be related to #1671 … 🙄

**Comment by sokai** [comment]
@mw80: Module "group_bookmarks" **may** be a solution at servers with central maintained groups.
But this issue is about autojoining (without maintaining central groups files) at the client. The client (Conversations) has a roster with groups. And if you are in/have joined a group and the server is restarted Conversations should re-autojoin to that groups. (Like I wished three years ago by #1671 …)
