### ISSUE TITLE
Feature Request: Automatic message deletion per chat

### ISSUE THREAD

**Issue by eku** [iNPUTmice/Conversations#2767]
#### General information

* **Version:** 1.23.3
* **Device:** Mi Max 2
* **Android Version:** 7.1 MIUI
* **Server name:** self hosted
* **Server software:** openfire
* **Installed server modules:** -
* **Conversations source:** PlayStore

The expert setting  ```Automatic message deletion``` applies to all chats. It would be nice to  configure this per chat, since chats with heavy traffic should be handled different than chats with low traffic.

**Comment by max421** [comment]
Hey is there a info somewhere about the status of the feature request? 
I would be also very happy if this would be possible (Thats only thing which i missed very much since i change from Signal to Conversations).

**Comment by licaon-kter** [comment]
@max421 Did you start coding yet? PRs welcomed... :wink:

**Comment by max421** [comment]
@licaon-kter Unfortunately I have only a little konwledge with programming and this isn't my world at all. So that's why i hope the dev/contributors make this feature possible. 

Of course i'm happy that there is a function at all in the expert settings (is better than nothing:)) but i would really appreciate if this feature become more extensive.
