### ISSUE TITLE
MUC private message are missing if i login again from the app or I clear history and try to restore the message

### ISSUE THREAD

**Issue by golangbu** [iNPUTmice/Conversations#2964]
#### General information

* **Device:** samsung S8
* **Android Version:** OREO
* **Server name:** conversations.im

* **Conversations source:** PlayStore,

#### Steps to reproduce

1. …Login with your username and password.Go to MUC where you have Private message with friends.
       All the message downloaded except the private message.
2. …Select a MUC.Click on the menu.Click on clear message then redownload the message the private message are not their.

#### Expected result
Private message should be redownload like other message in muc.

#### Actual result
Private message are not their after redownload. Private message should be their

**Comment by licaon-kter** [comment]
What type of MUC? Private? Public?

In a public&anonymous one you can't get them, imagine that another user logs in with the same nick...they should get your messages?

**Comment by pruthwirajs** [comment]
I am also facing this similar issue.
Private messages are not getting restore.

**Comment by iNPUTmice** [comment]
Some technical information since @niaomi mentioned in another issue they'd like to work on that.
group chat messages are stored on the group chat server. Private messages on the account. To retrieve private messages after clearing history they need to be explicitly retrieved from the account. Right now Conversations will only retrieve messages from the group chat server.

**Comment by golangbu** [comment]
Any updates on this @iNPUTmice
