### ISSUE TITLE
Ability to give group chats a custom name/alias

### ISSUE THREAD

**Issue by schiessle** [iNPUTmice/Conversations#3000]
Sometimes the name of group chats are not as obvious as I like. For IRC chats, which I join over a XMPP/IRC bridge, the room is named after the topic set in the IRC channel. Also for native MUC's the name is often not as obvious as I would prefer in order to distinguish all my open group chats. Therefore I think it would be good to have the ability to rename the chats, e.g. by giving them a local alias.

**Comment by mdosch** [comment]
Actually Conversations already supports this partly. MUC bookmarks stored with an alias via Gajim show that alias in the list to join a saved MUC but sadly shows the topic again after joining which makes it hard if you have several "Join the ..." MUCs instead of the short precise aliases you set for them.
