### ISSUE TITLE
switching in conversation crypto to OpenPGP

### ISSUE THREAD

**Issue by claravowel** [iNPUTmice/Conversations#3031]
#### General information

* **Version:** 2 latest fdroid
* **Device:** eg LG tribute 5
* **Android Version:** 511 stock
* **Server name:** eg conversations.im

#### Steps to reproduce

start conversations
pick existing conversation
change to pgp
create new key for xmpp jid
return to conversatoins
promted to sync or connect the two apps, yes

#### Expected result

some kind of progress or information

#### Actual result

An error has occurred

Unable to connect to OpenKeychain

every conversation now has this as the switch attempt result

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````
i dunno how to do this or I would have

**Comment by licaon-kter** [comment]
You need an USB connection to a PC, then with ADB get a log (logcat) of the moment when this happens (you'll need to redo the steps and reproduce the error). Use your favourite search engine to learn how to ADB...

**Comment by wiktor-k** [comment]
Interesting, I disabled and then reenabled OpenPGP and also get the same message. Maybe that's a regression or something due to OpenKeychain API changes.

I'll grab logs when I'm near the computer.

**Comment by wiktor-k** [comment]
Okay, in my case it was a weird UX interaction between Conversations and OpenKeychain. Even though I authorized access for Conversations when I double checked in OpenKeychain no keys were selected. Further checks are needed to see which app is at fault here.

The logs would show in this case:

```
05-17 14:30:48.046 20603 20603 D conversations: [redacted]: OpenKeychain error 'Key selected for encryption is not allowed' code=0
```

I guess Conversations could show that info to the user instead of generic 'unable to connect'. That info made me check OpenKeychain's keys permissions.
