### ISSUE TITLE
[Feature request] OMEMO MUC (group chat) with users with not accepted keys not possible

### ISSUE THREAD

**Issue by BlackLotus** [iNPUTmice/Conversations#3081]
#### General information

* **Version:** 2.2.2
* **Server software:** ejabberd 18.01
* **Installed server modules:** XEP 16, 45, 54, 163, 191, 198, 280, 313, 363
* **Conversations source:** F-Droid

#### Steps to reproduce
Create group chat add n persons with omemo and one without omemo keys.

#### Expected result
You should be able to write to the group.

#### Actual result
You aren't able to write to the group until you either remove the (possibly not even online) user without omemo, disable omemo or use a different client.

**Comment by licaon-kter** [comment]
Write to what group exactly? All the users with keys?

**Comment by BlackLotus** [comment]
Yes. 

If the group is members only you have to add every member that _should_ have access to it. You can't write to the group thought even if this member is offline.

If everybody uses omemo except one invited individual that hasn't got a key yet it's likely that he/she/it just hasn't come to generate one yet and/or is offline.

It should be possible to have a group chat with added members that have no omemo key on the server, even if it means that some people will receive no message in this group until they generated a key.

Gajim has such an implementation.

**Comment by licaon-kter** [comment]
I agree, it's a nuissance.

**Comment by CryptOwl** [comment]
Agreed here. If somebody without a key is invited to the MUC an OMEMO encrypted group chat becomes impossible until that person is kicked out or get a key. Gajim does indeed do a better job here.

**Comment by STPKITT** [comment]
IMO in the described case Conversations should automatically fallback to unencrypted chat. In my experience non-tech people prefer to have MUC working flawlessly while tech-people & peope that absolutely have to communicate encrypted know their stuff well enough so that they are not affected by this problem.

**Comment by licaon-kter** [comment]
@STPKITT Why? No, it should send the message to all the available people at the moment.

When the "lost" user comes online then add its key to the chat to receive messages too.

**Comment by STPKITT** [comment]
True, that's the ideal case, but this issue is also about users without any OMEMO capabilities.

> When the "lost" user comes online then add its key to the chat to receive messages too.
At least in a 1:1 chat when a user adds a new OMEMO key he will still not be able to decrypt messages sent before that, so I think that would not work in a MUC either.

**Comment by licaon-kter** [comment]
> True, that's the ideal case, but this issue is also about users without any OMEMO capabilities.

Really? Why would you invite a non-OMEMO user to your OMEMO MUC? The OP says "offline"

> so I think that would not work in a MUC either.

As expected, yes

**Comment by STPKITT** [comment]
> Really? Why would you invite a non-OMEMO user to your OMEMO MUC? The OP says "offline" not "without OMEMO"

The OP says "user without omemo, disable omemo or use a different client."
For most or non-tech people there isn't such a thing a OMEMO MUC. For them there is just MUC & if that MUC is encrypted it's very good, if not but at least it works it's still good.

**Comment by ritzmann** [comment]
We have been bumping into this issue each time an owner adds a user to a hidden room. It is not only annoying but also results in users falling back to unencrypted messages. What is happening is this:

1. Owner adds user/JID to hidden room.
2. Newly joined user does not go online for a couple of hours/days because they have other things to do.
3. Conversations sees that new JID was added, cannot retrieve OMEMO key of newly added user and refuses to send any OMEMO-protected message to the room.

The only way to send messages with Conversations to the room in this case is to either disable OMEMO or remove the newly added user from the room again.

Gajim behaves more gracefully in this case and sends OMEMO-protected messages. The newly added user won't be able to decrypt them of course but at least that is more secure than forcing other users to send unprotected messages.

**Comment by benjaminbischoff** [comment]
I support the approach of @ritzmann

**Comment by CryptOwl** [comment]
So, after all this time the problem still persists and it is as annoying as ever. While the OMEMO plugin for Gajim allows you to send encrypted messages to a MUC even while not all fingerprints are available we are still stuck with the "remove the problematic JID" approach in Conversations. By the way, removing JIDs via Conversations also means banning them from the MUC - this is another issue not to be discussed here.

I still think the current situation makes using OMEMO much harder than it should be. It's a HUGE hindrance for using OMEMO in MUCs (even in small ones) and for the adoption of OMEMO as a standard in XMPP in general. A solution for this like the Gajim approach has been proposed by @ritzmann.

@iNPUTmice: What is you perspective on this? Having the two most popular clients around (Gajim for desktop systems, Conversations for Android devices) with so different approaches gives this problem even more significance.

**Comment by sokai** [comment]
Bumping by a sticker seems not possible, so I'll ask @iNPUTmice: Can u plz fix it or tell us ur point of view? #thx

**Comment by licaon-kter** [comment]
> Newly joined user does not go online for a couple of hours/days because they have other things to do.

Is this the gist of the issue at hand? If so, it looks like a corner case.

The problem is that it sounds very odd: you need to add this contact yet the contact doesn't need to be added, since they don't really care _(or busy doing something better)_?

I feel that the proper way is: have them come online once _(eg. talk 1:1 at least to be sure things are in order OMEMO wise or human wise, maybe the account was hijacked?)_, **then** add them.

**Comment by ritzmann** [comment]
Well, so current model is: Rely on owner of hidden room to sync up with new member, otherwise all members of room will not be able to write OMEMO messages.

Alternative suggestion is: Keep allowing members to write OMEMO messages. New member will only be able to decrypt messages that are posted after she actually joined the room.

As far as I am concerned, the alternative is less confusing and easier for users without affecting confidentiality.

> talk 1:1 at least to be sure things are in order OMEMO wise or human wise, maybe the account was hijacked?

Asserting the identity in a E2E scenario always needs to be done through a separate channel and generally is very hard to do if you don't already know the person in real life.

**Comment by iNPUTmice** [comment]
I think people in this thread are mixing up different kinds of issues with OMEMO in group chats.

To quote the original post:

> Create group chat add n persons with omemo and one without omemo keys.
> You should be able to write to the group.

I disagree with that premise. That would result in that one person not getting your messages. What's the purpose of having that person in the group then in the first place? (Assuming that this person really doesn’t have any OMEMO keys at all; and it's not just another problem retrieving an existing key.)


Other people in this thread mention issues with users not being online; Which absolutely and never was a requirement. None of the recipients have to be online in order to send messages with them.

In the past you had to have mutual presence subscription with each participant but even that hasn’t been true in a while.


There is still a slight unsolved problem with users who have been added to rooms that have never been online before. But the only solution to that problem would be to ignore not being able to retrieve keys. And if we do that we might accidentally ignore non existing keys. And that's not desirable. In general (and with the exception of that one particular case) Conversations should not silently ignore errors.

**Comment by sokai** [comment]
Hey @iNPUTmice !

> Other people in this thread mention issues with users not being online; Which absolutely and never was a requirement. None of the recipients have to be online in order to send messages with them.
> 
> In the past you had to have mutual presence subscription with each participant but even that hasn’t been true in a while.

Have you seen #4131 ?

I have the exact situation you described above – keys from (two) offline accounts can't fetched by a (single) new JID in the MUC.
Do you may have a solution for this? – As mentioned, Gajim allows to send OMEMO messages for the new JID (in such a problematic MUC/situation). May it be possible for Conversations, too?

Thanks a lot and best regards!

**Comment by Ppjet6** [comment]
I'd like to add to the OP's case.

STPKITT wrote in https://github.com/iNPUTmice/Conversations/issues/3081#issuecomment-409865796
> [..] people that absolutely have to communicate encrypted know their stuff well enough so that they are not affected by this problem.

No, this is simply not true. People in need of e2ee are just like anybody else when it comes to technology, they need a fair amount of training before understanding the pros and cons and getting habits of doing or not doing specific things. We're not all equally well-versed in every domain.

In my circles messaging has only been a means to an end, we don't wake up every morning chanting to the e2ee gods. This gets harder when some are reluctant to using technology altogether.

iNPUTmice wrote in https://github.com/iNPUTmice/Conversations/issues/3081#issuecomment-633089859
> (Assuming that this person really doesn’t have any OMEMO keys at all; and it's not just another problem retrieving an existing key.)

Another possibility is the server of said person doesn't allow you to get to their keys before performing $ACTION. Say, a server with mod_strangers. But that's just an example, it doesn't actually matter to me why this happens.

> > Create group chat add n persons with omemo and one without omemo keys.
> > You should be able to write to the group.
> 
> I disagree with that premise. That would result in that one person not getting your messages. What's the purpose of having that person in the group then in the first place?

My use-case, and please let's not debate the use-case, I've already seen it dismissed so many times it's annoying:
- Private rooms
- Small-ish amount of people 3-20, (but possibly more). Not especially knowing each other directly or very well, even though there is some kind of trust going around
- Not all in contacts
- Using E2EE to counter a possibly compromised host (see riseup's document on why they encrypt mailboxes for example, we don't have this exact feature in XMPP but that's not impossible).

With this I can create a private room, invite people that don't necessarily know each other. It happened that some server was preventing users to fetch their keys. What to do in this case?
- You can't tell anyone in the room because you can't send messages
- You don't know why it's this way
- You don't especially have the expertise to know that disabling encryption might allow you to send
- You might not really want to disable encryption anyway

So you come back to me saying "Your thing is crap I can't use it".

First off, yes I would like servers not to have this behaviour, and at the same time, putting all your identities public (OMEMO devicelist/bundles) might not be the smartest. (slightly conflicted)

At least if we don't allow sending an encrypted message in this case, we might want to try being more explicit to the user (I don't remember the current error if there is any) so they get a clue. Like with whom it's blocking, why, and possible ways to solve the problem?

Note that if we allowed sending only to some participants, I would still like a message saying it's not everybody is going to be able to read.

**Comment by STPKITT** [comment]
@Ppjet6 I agree with you and also admit that in regards to the comment you quoted. In any case, fallback to non-encrypted or sending encrypted messages which not every group member will be able to decrypt, Conversations or rather any client needs to show the users a very clear (in case of non-encrypted: warning-) message telling them what's wrong.

**Comment by ambadyanands** [comment]
>> Create group chat add n persons with omemo and one without omemo keys. 
>> You should be able to write to the group.

> I disagree with that premise. That would result in that one person not getting your messages. What's the purpose of having that person in the group then in the first place? (Assuming that this person really doesn’t have any OMEMO keys at all; and it's not just another problem retrieving an existing key.)

Isn't one person not being able to decrypt the messages better than all the members in the group not being able to send any encrypted messages at all? (assuming that person could decrypt messages in future after successfully exchanging keys). It may not be a perfect solution, but it seems better than the current scenario.

**Comment by licaon-kter** [comment]
@ambadyanands they won't be able to decrypt past messages

Only messages from the moment they have their own key.

**Comment by ambadyanands** [comment]
@licaon-kter Yes, but isn't that still better than the whole group being forced to exchange unencrypted messages?

**Comment by licaon-kter** [comment]
@ambadyanands I agree, so better kick the user until they get a key. It's to no one's benefit to be in the group until then anyway.

**Comment by ambadyanands** [comment]
@licaon-kter Me and some of my friends know this solution. But what about non-techie people? How do they know this is what they got to do? The other solution, ignoring the newly added user until their key becomes available, requires no further action from group admins (like removing the problematic user and adding them back later) and makes the app more usable.

**Comment by licaon-kter** [comment]
Then maybe the message should say this, "_please remove user X until they get a compatible client"_ instead of continuing. Better than to see _"This message was not encrypted for your device but carry on everything is fine"_

**Comment by ambadyanands** [comment]
@licaon-kter let's agree to disagree and move on, thanks.

**Comment by Ppjet6** [comment]
> "please remove user X until they get a compatible client"

As mentioned in the room, this won't work, because not all users inviting people are owners, so they can't actually "remove" a user. This would have to be sent by the MUC itself, if that's the solution that was adopted.

As stated above my preferred solution is similar to @ambadyanands. But in any case, Conversations would need to tell something to the user. Either the one inviting, or the one trying to send. And I have already suggested directions above, not going to repeat myself.

**Comment by Ppjet6** [comment]
It seems to me that people are really stuck in this "don't lose messages" mantra, because they don't get confronted to this kind of situation and they don't see how annoying it sometimes is.

Don't get me wrong, I'd also prefer not to lose messages, but in this case the concerned users wouldn't see them anyways. So I think it's better exposed in the room so that all users can act on it, not just the concerned parties that may be clueless about it.

**Comment by STPKITT** [comment]
Sad thing is the several MUC issues including this one really are what makes people use other IM systems instead of XMPP & in case of Matrix users it's unlikely to ever win them back.

**Comment by licaon-kter** [comment]
@STPKITT do share how matrix solved this though

**Comment by onchainchapo** [comment]
@BlackLotus @licaon-kter @STPKITT Did anyone find a more graceful/Gajim-like solution for this?

**Comment by pravi** [comment]
@ambadyanands was suggesting (when we discussed this) the muc server keeping a copy of all members, this would at least solve servers going down temporarily or permanently.
