### ISSUE TITLE
Feature Request: Add call contact if on addressbook

### ISSUE THREAD

**Issue by tomamplius** [iNPUTmice/Conversations#3110]
Is it possible to add a button to make a call from the chat window with a contact if this contact is present in the address book with a telephone number

![call](https://user-images.githubusercontent.com/6951820/42561662-fb977f2a-84f9-11e8-879b-02f7e876739b.png)

**Comment by licaon-kter** [comment]
Needs extra scary permission...:unamused:

**Comment by tomamplius** [comment]
OK, that is just an idea, because i receive lot of message "call me when you can" , il need :
=> open address book
=> find contact
=> open contact form

Maybe just open contact form directly without launch call

**Comment by tomamplius** [comment]
Ok, it's done for me i will use that.
But it's not really intuitive to find this method. For the user experience of this (very good) application, it's can be improved.
But you can close this feature if you want

**Comment by brighterness** [comment]
> Needs extra scary permission.

Or partition fear with a plugin.  Only the plugin would request this frightening power.

I myself fear contacts integration because the contact's photo overrides the avatar shown in Conversations.

I would want the ability globally (but preferably per contact)

* show JID's uploaded avatar as priority
* show photo from contact that includes JID in 'IM' 'Jabber' as the priority
* show the avatar I have assigned her JID myself via Conversations as the priority

**Comment by Echolon** [comment]
I needs to be made clear to the user that the app is just referening to the phone normal call function and NOT using voip - as lots of people otherwise think they can use wifi traffic to make international calls.

However, an option to refer to a JitsiMeet session or Nextcloud session would be interesting too

**Comment by licaon-kter** [comment]
This can be closed now I guess.
