### ISSUE TITLE
[Feature Request] Introduce an possibility to display an avatar enlarged

### ISSUE THREAD

**Issue by alexara** [iNPUTmice/Conversations#3151]
#### General information

* **Version:** 2.2.8

#### Issue

Avatars are displayed very small in a conversation and in the contact details and therefore it is hard to see any details. 

#### Proposed solution

1) add an enlarged version of the avatar in the contact details
2) introduce the possibility to enlarge an avatar of a user who is not in one's roster, e.g. a participant in a public muc

**Comment by brighterness** [comment]
This code apparently already exists in Pix-Art Messenger a fork of Conversations.

**Comment by zz-ha-dum** [comment]
extend this with an option to display avatars larger in every conversation thread

**Comment by licaon-kter** [comment]
Would be nice, true...

**Comment by iNPUTmice** [comment]
We currently have no proper way of storing large avatars on XMPP.

**Comment by licaon-kter** [comment]
And PAM shows what exactly?

**Comment by iNPUTmice** [comment]
> And PAM shows what exactly?

I believe it just increases the resolution to a point where it is dangerously unsustainable and will put an enormous load on the home server (putting huge base64 encodes images in a database) and might not even work well across the ecosystem due to stanza size limitations.

PAM being "oh it's so easy let's just increase this constant here and avatars are pretty" but not understanding the consequences of that decision is basically PAM in a nutshell.

Avatars of that size belong on HTTP; not base64 encoded in a database; but we don’t have a mechanism in XMPP do store them permanently.

That's not to say that I wouldn’t want for such a mechanism to exist. But I rather do things right.
