### ISSUE TITLE
Openkeychain not detected

### ISSUE THREAD

**Issue by mase76** [iNPUTmice/Conversations#3410]
Hi!
Conversations does not play with Openkeychain any more. Openkeychain seems not to be detected. I am told, that the recepients key was not published, but I have it in my keyring. Also I am not able to decrypt messages sent to me. I use Conversations and Openkeychain fron F-droid

**Comment by licaon-kter** [comment]
Logcat ?

**Comment by mase76** [comment]
Nothing to see in Logcat. The keys of new contacts seem not to be published, and ny key not to them. When the keys have already been published in the past, the crypto works.

**Comment by licaon-kter** [comment]
Conversations doesn't log anything when you try? Neither does OponKeychain?

**Comment by mase76** [comment]
I see nothing related to this. However my key is shown in my account settings. The guy on the other side, where it did not work, gave up already. I had imported his key into okc, and he did so with mine. However nobody was able to send an gpg encrypted message.

**Comment by iNPUTmice** [comment]
Please be more specific about what kind of error messages you are seeing and where.
Both parties have to 'publish their key' by long pressing on the account in 'Manage Accounts'.
You always had to import the key in open key chain. 'Publishing the key' just tells other people your key id essentially. If your Conversations detects the successfully published key id of the other party it will guide you to import it through OpenKeychain.

If Openkeychain got updated (or otherwise force restarted) you might have to restart Conversations as well (kill app over app details).

PGP works fine on my end with the latest OpenKeychain version and the latest Conversations version.

**Comment by mase76** [comment]
I tested again with another guy. This time it worked. Maybe the other guy was holding it wrong. Maybe we could close this, until I have further information.

**Comment by HackM3nt3** [comment]
I have the same problem with openkeychain from F-droid, if i use openkeychain from google play store works fine but if i use a different version of openkeychain it doesn't work. it seems that the 2 apps need an internal way to link themselfs and F-droids apps don't have the proper links.....

**Comment by licaon-kter** [comment]
@HackM3nt3 don't they have the same app id?

**Comment by HackM3nt3** [comment]
i though that the problem was with compiled openkeychain apk but i tried with the google store openkeychain apk i had the same problem.....
![IMG_2556](https://user-images.githubusercontent.com/13055051/54569266-2ecc8700-49a8-11e9-9a7e-02edf909192f.JPG)
