### ISSUE TITLE
text/html OOB links render as button and open page locally

### ISSUE THREAD

**Issue by SamWhited** [iNPUTmice/Conversations#3414]
Some clients (I think it's ChatSecure on iOS sending these) send links with an OOB data pointing to the web page. In Conversations this renders a scary button that says "Open text/html" and hides the actual link. This feels suboptimal. When you click the button, it downloads the HTML and attempts to open it from the local file.
For example, I got a message like this earlier:

```xml
<message from="" type="groupchat" id="" xmlns="jabber:client">
<x xmlns="jabber:x:oob">
<url>https://lcamtuf.blogspot.com/2014/11/pulling-jpegs-out-of-thin-air.html?m=1</url>
</x>
<body>https://lcamtuf.blogspot.com/2014/11/pulling-jpegs-out-of-thin-air.html?m=1</body>
</message>
```

Instead, it would make sense to me to just show the link for anything that returns a content type of HTML.

**Comment by iNPUTmice** [comment]
We don’t actually look at the content type. We just look at the file extension. So trying to detect if there is a normal website behind the link will quickly fall apart. I suggest not sticking normal links in oob tags. Do you know what client sent this?

**Comment by ValdikSS** [comment]
Conversations does not show message body if `jabber:x:oob` is present in the message. See https://github.com/siacs/Conversations/issues/3419#issuecomment-478561197

For [Matterbridge](https://github.com/42wim/matterbridge), I had to send two messages instead of one: first with body with link, second with OOB data only.
