### ISSUE TITLE
[Feature request] Change password button

### ISSUE THREAD

**Issue by meaz** [iNPUTmice/Conversations#3424]
I've noticed that some users have troubles finding where they can change their password. Also, some of them think that in the account details, if they change the actual password, that means it changes the password on the server (!)...
I suggest to add a button to change the password just under the username and the password to avoid those two problems and make thinks simpler.
![Screenshot_20190402-130647](https://user-images.githubusercontent.com/13604424/55399827-79273980-554c-11e9-99e3-d4c6e94ca6fb.png)

**Comment by licaon-kter** [comment]
Even in your mock-up things are confusing, so if I write the password there will it login or change it? Or the button opens the other view where you change it? 

It's not clear right away.

I prefer having the "change password action" separate.

**Comment by meaz** [comment]
and if your replace "password" by "actual password" ?
![Screenshot_20190402-130647](https://user-images.githubusercontent.com/13604424/55402150-01a8d880-5553-11e9-9781-a624011c899f.png)

**Comment by badrihippo** [comment]
Perhaps "current password" would work (at least in English). Then it'll be clear that you have to type it in first, regardless of whether you're changing your password or just setting what's already been changed elsewhere.

I'd also suggest a notification saying "This sets only the setting here, not the actual password, are you sure you want to continue?". The reason is, people sometimes edit it thinking they're changing the password, and then end up losing access since they forgot what the original password was.

Or to make it smarter, we could do something like this:

* If the *last* login was successful, say "are you sure you want to set the current password? This is different from actually changing it on the server using the 'Change password' button" (if the login failed then they probably changed the password externally and know what they're doing)
* After changing, if the login is not successful, say "new password login failed, do you want to change it back?". This would require caching the old password for a short period of time.

That would help avoid common errors that users (or at least a couple of my friends) have made.

Finally, would it make sense to **disable setting the current password** unless a login is unsuccessful? I mean show only the "change password" option and not "set current password" option. If the login was successful, there's no reason for the setting to be modified at all.
