### ISSUE TITLE
Simultaneous classic voice call and Conversations call issues

### ISSUE THREAD

**Issue by heurekus** [iNPUTmice/Conversations#3746]
#### General information

* **Version:** 2.8.3+fcr
* **Device:** Samsung S9 
* **Android Version:**  Android 8 - Lineage OS
* **Server name:** self hosted
* **Server software:** Prosody
* **Installed server modules:** 
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Make a 'normal' voice call in the cellular network on device A. Call is ongoing.
2. Take another device (B) and establish a CONVERSATIONS voice call to device A.
3. Device A shows incoming call from Conversations. User can accept the call
4. User can hear and talk 'into' the normal call and into the Conversations call at the same time
5. User can be heard in both calls
6. The remote ends can not hear each other (obviously, it's two different apps)

Main problem: The user is not aware that he is suddenly talking to two persons, as from a traditional UI perspective, an accepted incoming call during another call puts the first call on hold.

There could be different approaches to improve this behavior:

1. Reject the incoming Conversations call with a "busy" indication
2. Let the Conversations call come through, let the user accept it and automatically put the 'normal' call on hold. When the Conversation calls ends, the normal call is 'unheld'
3. Make a 3-way call out of this.

I guess 2. and 3. are not really feasible or overly complex to implement but I thought I'd mention them anyway for completeness.

Further: The reverse scenario, i.e. Conversations call is running and a 'normal' call comes in should also be considered.

**Comment by iNPUTmice** [comment]
1 and 2 require intrusive permissions from the operating system and it was a design decision not to request that permission. In turn this means that the user has to figure out what to do with normal phone calls by themselves. But I think that's ok.

**Comment by licaon-kter** [comment]
I find this limitation infuriating, this alone makes calls a feature you can advertise but I end up not wanting to use (not news, right? https://nitter.net/iNPUTmice/status/1271346284721582080 )

When I call I don't know why a contact does not answer, maybe they don't hear it (vibrate/silenced), but more often than not they are in a normal call.

When that happens I don't know that's the case, they don't know that I've called during the call, they don't know that I've called after their call either (no missed call notification), basically there was never a call from their POV.

Write a message you say? Yes, although I pressed the call button to call...ok...lets write, but....during their call they don't get notified of my message either, they might have notifications from the appmso this one is not special, also they'll put the device back in the pocket or on the table after hanging up out of reflex. So I'll need to write another message later on...again.

But no, I won't write a message because, apparently, not using Conversations is easier in the end, I call them using normal calls, and they get notified, and they answer and so on...as expected.

Can this have another go? Hide it behind an expert setting?

**Comment by iNPUTmice** [comment]
Fixed in 91e94db747792746487155b94d7c2caca94e5c9a and d158eeaf723002a7aab1833f9eb4dc5a66f32a24
