### ISSUE TITLE
Issues previewing and sharing SVGs

### ISSUE THREAD

**Issue by contrapunctus-1** [iNPUTmice/Conversations#3773]
In Gajim, I sent someone an SVG. In Conversations, it is displayed as a file, not an image. Long press -> Share -> Conversations results in "This is not an image", so I can't share it with someone else.

Conversations v2.8.5+fcr from F-Droid

**Comment by licaon-kter** [comment]
What application has registered itself as able to open SVGs?

Conversations gets whatever your default Gallery app offers, also FYI it already knows it's an image: https://github.com/iNPUTmice/Conversations/blob/41ada3480cbb0fd3948ddd7630ca8cb9676ab585/src/main/java/eu/siacs/conversations/utils/MimeUtils.java#L280

**Comment by ecxod** [comment]
Hello Liacon, thank you for the answer, but it looks like on cheogram that is a conversations fork this problem is somehow solved. I tested it on a android 6+ that can not display svg on conversations and it has no problem displaying svg on cheogram. Maybe we could see how they solved it and apply on conversations.

**Comment by licaon-kter** [comment]
Again, Conversations does not display them... it deffers them to your local system.

If Cheogram does, it's something else.
