### ISSUE TITLE
Support XEP-0373 OpenPGP for XMPP (OX)

### ISSUE THREAD

**Issue by mdosch** [iNPUTmice/Conversations#3813]
I would appreciate if Conversations would support [XEP-0373 OpenPGP for XMPP](https://xmpp.org/extensions/xep-0373.html) (OX).
You can find more informations about OX in the [xmpp.org wiki](https://wiki.xmpp.org/web/Tech_pages/OX). The wiki also has a [comparison of the different XMPP e2e solutions](https://wiki.xmpp.org/web/XMPP_E2E_Security).

**Comment by iNPUTmice** [comment]
I’m aware of OX but for now I’m not sure what the immediate benefits would be to introduce a third E2EE. Especially since OX is virtually none existent in the XMPP ecosystem. Of course if the wider ecosystem decides to move in that direction we can reconsider but I don’t think this is something that Conversations needs to take the lead on.

**Comment by mdosch** [comment]
I understand that you don't want to put this on the roadmap and rather wait whether it gets widespread adoption or not. But why don't you leave this issue open instead of closing it? Closing it gives the impression that you are opposed to implement it at any time or accepting a MR for it.

**Comment by iNPUTmice** [comment]
The issue tracker serves as a reminder / TODO list for me. I'm usually
pretty aware of new XEPs and the implementation status in other clients.
Therefor a reminder is unnecessary and only clutters up my todo list.
