### ISSUE TITLE
Feauture request: ability to register MUC nickname

### ISSUE THREAD

**Issue by NyanHime** [iNPUTmice/Conversations#3818]
It would be good to be able to [reserve](https://xmpp.org/extensions/xep-0045.html#register) your nickname in MUC to prevent impostering or accidentally conflicts.

**Comment by iNPUTmice** [comment]
Given that `user` and `user ` are both valid and different nicks imposter protection seems like a pointless exercise at this point.

Additionally I think that registering with MUC isn’t completely thought out (no obvious, implemented way to unregistered, servers don’t force you to use the nick you registered leading to additional confusion.)

If anything we want registration to happen automatically (instead of providing UI for that) but given the limitations described above I don’t think the user experience would be good.
