### ISSUE TITLE
Emoji: Conversations parses send Emoji differently

### ISSUE THREAD

**Issue by Echolon** [iNPUTmice/Conversations#3819]
#### General information

* **Version:** 2.8.7+fcr
* **Android Version:**  Android 7.1.2
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Send these four emojis from e.g. Dino: 🙅‍♂️️🙆‍♂️️🤦‍♂️️🤦‍♂️️
2. Review chat in Conversations and see each emoji twice.

#### Expected result

In Dino:
![dino123](https://user-images.githubusercontent.com/29168011/86636147-3ddbac00-bfd4-11ea-95fb-f403592ce92d.png)

#### Actual result

In Conversations
![Screenshot_20200706-215642](https://user-images.githubusercontent.com/29168011/86635819-e2112300-bfd3-11ea-90f8-031d6e90571c.png)

#### Additional points

- History: https://logs.xmpp.org/commteam/2020-07-06#2020-07-06-87caed30d601b091

- @mar-v-in thanks for reviewing from your side. I will quote your post:

> interesting. So dino sends [person gesuring no][join][male symbol][emojify][emojify]
> This makes sense to some degree, but [emojify] is often not needed.
> [male symbol] = ♂
> [male symbol][emojify] = ♂️
> [person gesturing no] = 🙅
> [person gesturing no][join][male symbol] = 🙅‍♂
> [person gesturing no][join][male symbol][emojify] = 🙅‍♂️
> [person gesturing no][join][male symbol][emojify][emojify] = 🙅‍♂️️
> [person gesturing no][join][male symbol][emojify][emojify][emojify] = 🙅‍♂️️️

**Comment by iNPUTmice** [comment]
@mar-v-in there are two and more emojifies? Is that intentional?

**Comment by mar-v-in** [comment]
Both emojify (VS16) are useless here because [person gesturing no][join][male symbol] is only defined as an emoji in Unicode. Technically there is nothing wrong with adding arbitrarily many emojify. Having multiple emojifies directly after each other is completely useless and probably caused by a bug GTK (it joins person with male emoji as suggested by specification and then tries to emojify the result which is not possible and double emojifies the male symbol instead)

It's important to note though that the additional emojify don't seem to cause issues in Conversations as far as I can see. From the message above, only the non-emojified male symbol and the person without gender being joined are correctly rendered in my Conversations on Android 10. The variations with one, two and there emojifies display all the same.

**Comment by mar-v-in** [comment]
Also interestingly when you copy the message above (from the history linked because GitHub probably messes with the bytes) into Conversations it displays everything correct in the input box, but after sending it displays thing very wrong.

![](https://i.imgur.com/tX2nheR.png)

**Comment by singpolyma** [comment]
This issue seems like it is recurring for me.  @iNPUTmice do you recall what the nature of the fix was here? The diff seem to be a whole file rewrite :)
