### ISSUE TITLE
XEP-0033 support for jmp.chat users

### ISSUE THREAD

**Issue by oathzed** [iNPUTmice/Conversations#3844]
Can we please get xep-0033 multi-recipient message chain support for jmp.chat users, as this can completely replace your phone number. thanks!

#### General information

* **Version:** 2.8.10-beta+pcr
* **Device:** google pixel 2
* **Android Version:**  android 10
* **Server name:** dismail.de
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. make a multi-recipient message chain with number,number,number@cheogram format
2. have them send you something, they will just show as number format and not as contact name in your contacts

#### Expected result

for your contacts names to show in the multi-recipient message chain instead of just their number

#### Actual result

you see just the phone number

**Comment by iNPUTmice** [comment]
XEP-0033 doesn’t contain enough information to magically just have group chats. XEP-0033 might be a building block for that but in itself it's not "Group Chats". Is there any documentation available on how exactly JMP uses XEP-0033 to create group chats? @singpolyma

**Comment by singpolyma** [comment]
I will provide all needed context here, even if I believe readers will already know it, for completeness.

Cheogram (and the primary commercial direct message route, JMP.chat, run by @ossguy) is a mapping / bridge to give every telephone number a JID.  The most common use of this is to translate XMPP stanzas into SMS or MMS messages, and to receive SMS or MMS messages as XMPP stanzas.

MMS contains a feature which allows sending a message to a list of phone numbers.  This MMS feature maps to an obvious subset of XEP-0033.  So if cheogram receives an XEP-0033 stanza at `cheogram.com` (and the configured backend route for the source JID supports MMS) it will send a multi-recipient MMS.  Addressing may be done using XEP-0033 URI addressing (`sms:` scheme) or JIDs `@cheogram.com`.

Inbound MMS with multiple recipients may be sent by Cheogram to the target, including XEP-0033 information (with all but the current target specified as `delivered` since the phone network has delivered those copies) that specifies the other recipients of the message (currently as `sms:` URIs, but that could easily be changed).

Since no known client has UI to show the other recipients specified in a received XEP-0033 message, Cheogram actually defaults to a fallback mode where instead of using XEP-0033 it sends the message as from `tel1,tel2,tel3@cheogram.com` so that the full recipient list is visible.  This is a terrible hack for many reasons, but the one most often complained about is that many users do not know the phone numbers of their contacts on sight, and this has of course no way of integrating into their roster to show their preferred name for the contacts.

Since many popular cell phone MMS UIs show such multi-recipient messages threaded based on the recipient list, and default replies to "reply-all", many users call this functionality "group text" or "group chat' even though it does not have the features of a MUC and would map to MUC usage quite poorly (though hacks in that direction may be explored in the future alongside the current fallback).

Hopefully this provides enough context about how Soprani.ca family projects are currently using XEP-0033 (Cheogram-SMTP will likely use similar for SMTP Cc and multiple-to headers as well when it is done) and what might have been meant by OP.

**Comment by iNPUTmice** [comment]
So inbound messages are currently coming from `tel1,tel2,tel3@cheogram.com` AND have `<addresses/>`?

How does one know who originally sent the message if the from is te1,tel2,tel3?

**Comment by singpolyma** [comment]
>So inbound messages are currently coming from `tel1,tel2,tel3@cheogram.com` 
>AND have `<addresses/>`?

No, it is or. The tel1,tel2 hack is just a fallback mode.

**Comment by iNPUTmice** [comment]
Is there any automatic detection for what mode to use?

**Comment by singpolyma** [comment]
>Is there any automatic detection for what mode to use?

Not in production right now. We've considered doing it by service discovery, 
but afraid that if one client adds support it'll be a very uneven experience 
across a user's clients.  So it may end up staying a manual switch.

**Comment by iNPUTmice** [comment]
While group chats over XEP-0033 are certainly an interesting concept they demand for a broader discussion and more planning than just quickly doing it for jmp.chat.

I’ll try to get a mailing list discussion going.
