### ISSUE TITLE
Increase JPEG quality for compressed images

### ISSUE THREAD

**Issue by Nekun** [iNPUTmice/Conversations#3903]
At this moment, Conversations by default compresses uploaded images by transcoding them to JPEG with 75% of quality. For many cases (e.g. exchanging of artworks) it produces rather poor results, with strongly marked JPEG artifacts. Here a screenshot for example, as you can see when expand it to 1:1, there is moire around text makes it harder and unpleasant to read. Maybe quality for compressed images in widespread 4G+ era should be higher, 85-90%, or use modern formats for compression instead of JPEG?

![qCiBjwX_QrmmOv1pTfaBDg_0198268f08](https://user-images.githubusercontent.com/65838015/95942954-07cc7600-0dd4-11eb-8f37-0a6f9af103e4.jpg)

**Comment by licaon-kter** [comment]
HEIF support covers which Android versions exactly?

**Comment by iNPUTmice** [comment]
Are we talking about avatars? Because the screenshot doesn’t show any images.

Avatars currently are under very strict size restrictions which doesn’t allow us to make them larger and still be compatible with a broad range of XMPP servers. Like wise we can’t simply use other compression formats in order to remain compatible with other XMPP clients.

For attached images I suggest you use 'Attach file' instead which sends images uncompressed.

**Comment by Nekun** [comment]
@iNPUTmice No, my issue not about avatars, but about images sent through HTTP File Upload. Screenshot is a such image itself.

I know that sending via 'Attach file' leaves image unchanged, but many people who use Conversations don't know about enabled by default image compression and sends it in poor quality, and this is inconvenient (or ever impossible sometimes) to ask for resend image as 'file' everytime. Maybe some warning about compression should be display or, as I propose in beginning, increase compressing quality to reasonable values?
