### ISSUE TITLE
Feature Request: XEP-0434 and XEP-0450

### ISSUE THREAD

**Issue by jf99** [iNPUTmice/Conversations#3958]
[XEP-434: Trust Messages](https://xmpp.org/extensions/xep-0434.html)
[XEP-450: Automatic Trust Messages](https://xmpp.org/extensions/xep-0450.html)

These two are fundamental to actually use OMEMO in a secure and convenient way in real-world scenarios with multiple devices per user and users replacing their devices from time to time. Currently, users usually fall back to blind trust in such cases. This issue replaces #3417, I guess. I am willing to spend some money on this, if it helps.

Both XEPs are from a Kaidan author, although I don't think any messenger has implemented them, yet.

**Comment by iNPUTmice** [comment]
I’m highly skeptical  of Trust Messages / ATT.

If one wants to go down the cross signing path, I believe it would be a whole lot simpler (as in; easier to implement, less error prone, better to debug) to store the cross signing state in a server side PEP node instead of maintaining state purely in the client. (Matrix.org had a similar approach with server side storage.)

Orthogonal to that I'm still not convinced that n-way cross signing is indeed a good idea (partially for the reasons outline in the other thread.)

Figuring out what users actually want is a bit tricky¹ but I’m starting to suspect that users actually don’t want forward secrecy and cross signing therefore won’t solve any issues. Take Threema for example. The fact that it doesn’t have forward secrecy very rarely, comes up.

As far as the ecosystem is concerned OMEMO is already a bit difficult to implement correctly. ATT will make that 10x worse. And a lot of the issues people are having with OMEMO (not the ones related to trust) are coming from the fact that people don’t implement OMEMO fully with all the little 'tricks'. I don’t want to imagine what introducing an even more complex system will do.
Meaning long term it might be better to take a few steps back and look at a less complex system like OX.

That being said I’m happy to be proven wrong on that; that's the XEPs have been accepted as experimental (with my vote); But I simply don’t believe enough in the concept to be the one doing the experimenting.

¹: For example OMEMO works just fine for me in day to day life and I have quite a lot of non-technical friends. I guess my friends don’t have new phones all the time and I also never verify. (Except on rare occasions with friends who actually do know what they are doing.)

**Comment by jf99** [comment]
> Figuring out what users actually want is a bit tricky¹ but I’m starting to suspect that users actually don’t want forward secrecy

Well, what kind of users are you talking about? To be honest, I believe that most "normal" users don't even care about E2E encryption at all. Nerds do that (at least some of them). Doesn't mean we don't need it though :P. On the other hand, I don't think even the average Joe is against forward secrecy. He just expects to see the message log of his old device on his new device as well (which is on principle possible with forward secrecy, by transmitting the messages between the devices at the moment of cross-signing).

> and cross signing therefore won’t solve any issues.

Wait, what? It solves the issue of having to scan the QR code of each new device with each of its contacts. I don't see how forward secrecy is related to that.

> And a lot of the issues people are having with OMEMO (not the ones related to trust) are coming from the fact that people don’t implement OMEMO fully with all the little 'tricks'.

Is there a complete list of all those little tricks somewhere? Because the way you say this, it sounds like a matter of insufficient documentation.

> That being said I’m happy to be proven wrong on that

Does that mean, if someone successfully implements it in their messenger without much headache, you will implement it in yours as well? Because if Conversations won't support it, there is no point in implementing it at all. > 80% of my contacts use Conversations (I don't because I don't have an Android device).

Thanks for the super quick reply, btw.

**Comment by iNPUTmice** [comment]
>> and cross signing therefore won’t solve any issues.

> Wait, what? It solves the issue of having to scan the QR code of each new device with each of its contacts. I don't see how forward secrecy is related to that.

What I meant to say is: Won’t solve the right issues.

Assuming OMEMO has a usability problem I think a more straight forward solution would be to move to a single, verifiable, identity. (Instead of the multiple ones that OMEMO has.)

This could be achieved with two different approaches both of which have been discussed in the community.

a) Introduce an identity key that acts as a trust anchor to sign OMEMO identities.
b) Move to a different encryption system (probably OX) that only has one identity key in the first place

Both (a) and (b) are tremendous tasks that probably wouldn’t share a lot of code. It's unlikely that both will happen (in Conversations or the larger ecosystem.)

That's where the question of "will a wider ecosystem benefit from forward secrecy" comes in.

>  Because if Conversations won't support it, there is no point in implementing it at all. 

I’m under the impression that it will be implemented regardless of what I think. (Which is a good thing)
