### ISSUE TITLE
Include UnifiedPush lib

### ISSUE THREAD

**Issue by iiitomo** [iNPUTmice/Conversations#4014]
I wish Conversations allows me choose my distributor for Push Notifications. (e.g. so that I can use Gotify instead of FCM / Google services)

UnifiedPush is a recent FOSS library that allows this, I suggest to include it in Conversations (and Quicksy). 

See https://unifiedpush.org and Matrix discussion #unifiedpush:matrix.org

**Comment by licaon-kter** [comment]
Do you have a reliability issue without Google Push?

**Comment by iNPUTmice** [comment]
I can almost guarantee you that XMPP is a better, more reliable push mechanism than any of the alternative providers offered through UnifiedPush.

If OpenPush doesn’t get integrated into F-Droid Conversations will become a push provider.

**Comment by iiitomo** [comment]
thx for your fast answers, and by the way big thx both for your contributions to FOSS community, I saw you are very active!
@licaon-kter : no. My goal is to avoid FCM on all apps I use, so that I can ultimately get rid of google services.
@iNPUTmice : do you mean all XMPP apps have push without FCM ? if yes, that's great :)  I didn't understand your remark about Conversations becoming push provider.

**Comment by iNPUTmice** [comment]
> do you mean all XMPP apps have push without FCM

Yes

**Comment by licaon-kter** [comment]
https://fedilab.app/wiki/features/push-notifications/

**Comment by rhclayto** [comment]
> I can almost guarantee you that XMPP is a better, more reliable push mechanism than any of the alternative providers offered through UnifiedPush.
> 
> If OpenPush doesn’t get integrated into F-Droid Conversations will become a push provider.

It would seem OpenPush is discontinued, & the developer suggest UnifiedPush as an alternative. https://bubu1.eu/openpush/

Id there any roadmap for having an XMPP native push mechanism working in Conversations? I have so many apps running with their own connections to receive messages (XMPP, SIP, Signal, etc), using lots of battery. It would be advantageous to have something like UnifiedPush that would allow many apps that need push services to run off of one push distributor.

**Comment by licaon-kter** [comment]
@rhclayto you're gonna PR support in those other apps?

**Comment by rhclayto** [comment]
> @rhclayto you're gonna PR support in those other apps?

Possibly.

Several already have UnifiedPush support (FindMyDevice, SchildiChat). Every new app that supports some kind of common push service eliminates an app that has to keep running all the time with its own connection.

**Comment by xundeenergie** [comment]
if conversations would be able to use unifiedpush, i can use gotify/gotifyup or nextcloud/nextpush to get notifications not only for conversations.

**Comment by xundeenergie** [comment]
or do you know this?

https://f-droid.org/de/2018/09/03/replacing-gcm-in-tutanota.html

this sounds also very interesting.

**Comment by mcg-android** [comment]
> Is there any roadmap for [...]? It would be advantageous to have something like UnifiedPush [...] that would allow many apps that need push services to run off of one push distributor.

Quoting @iNPUTmice in https://github.com/iNPUTmice/Conversations/issues/4216#issuecomment-955651525:
> This is interesting from a technical standpoint and there will probably be some experiments once Ltt.rs is out and Conversations 3.x is done

**Comment by xundeenergie** [comment]
> > Is there any roadmap for [...]? It would be advantageous to have something like UnifiedPush [...] that would allow many apps that need push services to run off of one push distributor.
> 
> Quoting @iNPUTmice in [#4216 (comment)](https://github.com/iNPUTmice/Conversations/issues/4216#issuecomment-955651525):
> 
> > This is interesting from a technical standpoint and there will probably be some experiments once Ltt.rs is out and Conversations 3.x is done

I interpreted this answer to another topic... make conversations a distributor for unifiedpush. So conversations should do the work of gotify-up or nextpush on an android. 
but THIS issue is to add unifiedpush-libs to conversations, to be able to use another push-provider for conversations. In other words, conversations shouldn't do the search for itself, it should be notified via unifiedpush the same way as via GCM/FCM on playstore-version - but via unifiedpush... use nextpush or gotify-up to get notifications.

And the link to f-droid and tutanotas story is a hint to avoid the permanent notification hold the app awake... (it's annoying to have all the time a notification for conversations and fairemail and other app, which should not sleep... tutanota found a way to solve this!)

**Comment by mcg-android** [comment]
> but THIS issue is to add unifiedpush-libs to conversations, to be able to use another push-provider for conversations. [...] use nextpush or gotify-up to get notifications.

Looks like I may have misunderstood this issue's topic. I'm not sure I'm the only one, though. :-)

So you'd like Conversations to use a locally running UnifiedPush Distributor (e.g. Gotify-UP). Conversations should probably no longer keep connections established to the XMPP servers when waiting for something to happen. And the XMPP servers shall tell the Distributor's Provider when something has happened, so that Conversations gets woken up and re-establishes a connection to the respective XMPP server.

If I understand correctly, ejabberd and Prosody can send messages to (offline) XMPP clients via FCM. Can they also do that via a UnifiedPush Provider? (Or is there a UnifiedPush Distributor app making use of FCM? Anyway, OP's goal was to avoid the use of Google's services.)

The advantage I see is a reduction of Conversation's (quite low) battery usage to zero when idling – and possibly one permanent notification icon less. Anything else?

A disadvantage would be the introduction of an additional possible point of failure. But maybe Conversations could wake up every now and then to actively check for new messages directly with the XMPP servers?

**Comment by licaon-kter** [comment]
It can't wake up, that's the point it depends on "some other external server" another SPOF, but now it's not Google but "app dev".

In a decentralized, federated network, like XMPP, there's no NEED (nor reason) for the app developer to be involved in each message being send from random server to random server.

Oh, some monopolies forcing themselves in between users and their messages? That's a sad situation indeed. But better vote with your wallet instead.

**Comment by xundeenergie** [comment]
yes. the goal is to avoid gcm/fcm toralky, to replace it with a selfhosted push-service which replaces fcm. so on a smartphone only one service is kept alive (gotify-up or nextpush), which receives notifications for serverals selfhosted services like xmpp, matrix, fediverse-services or email. 

tutanota found a way to realize it without a permanent notification and a small energyfootprint. they do it wit SSE (Server Sent Events) and a job-scheduling... it could replace gcm/fcm totally, if it would be integrated with unifiedpush... 

if no such service is available on a phone, the solution now used can be used then...

**Comment by xundeenergie** [comment]
> It can't wake up, that's the point it depends on "some other external server" another SPOF, but now it's not Google but "app dev".
> 
> In a decentralized, federated network, like XMPP, there's no NEED (nor reason) for the app developer to be involved in each message being send from random server to random server.
> 
> Oh, some monopolies forcing themselves in between users and their messages? That's a sad situation indeed. But better vote with your wallet instead.

you can host your own with https://ntfy.sh for example...

**Comment by simontretter** [comment]
@iNPUTmice It's great that conversations can act as a distributor. Any chance it will also be able to use one like NextPush (for the reasons outlined in this thread)?

**Comment by licaon-kter** [comment]
@simontretter read above https://github.com/iNPUTmice/Conversations/issues/4014#issuecomment-783151358
