### ISSUE TITLE
Move to a better place!

### ISSUE THREAD

**Issue by soheilkhanalipur** [iNPUTmice/Conversations#4089]
Unfortunately, I have to say that you have put this program in a bad place! GitHub!
This app deserves places like: Codeberg, Gitea, GitLab (Instances), and wherever better…
GitHub boycotts users, removes apps, and actually says "Whatever I want is going to be saved and whatever I don't need Is going to be deleted." The app has not paid attention to users' requests for RTL support for years, and says this is not a priority!
Free software should be free somewhere, which GitHub does not have!
Aren't these enough to leave GitHub?

**Comment by iNPUTmice** [comment]
I've actually though about this recently. Not necessarily with regards to Conversations but also the other projects that I run.

I’m perfectly capable of hosting my git repository on a personal server. In fact I do host my own git for some private projects. However Github is more than a place that hosts my git repositories. It is a social network. Think of stars and sponsoring or even the user pages. And while I do see the justified criticism of Github due to the network effect it is difficult to replace. Moving to Codeberg or Gitlab would solve the "where do I host my files" problem (again, I can do that myself) but it doesn’t replace the social network.

It's OK if you don’t want to use Github. There are other places like the XMPP group chat where you can interact with us.
