### ISSUE TITLE
Please make the 42 days thing optional in the settings of the client

### ISSUE THREAD

**Issue by ecxod** [iNPUTmice/Conversations#4147]
# This post is a bug report and a feature request in one.
So in a nutshell:
At the moment in encrypted groups where you only read and do not write a word, after 42 days your own fingerprints are deleted by the other users. This feature should be selectable. There are groups in which only one or two people write and the rest of the group only reads along, and the users are then prevented from reading along.

It is already clear to me that everyone in the group must turn off the feature. 

This was probably intended to remove fingerprints that were not used after 42 days. But at the moment users who are online every day are prevented from reading because the rest of the users delete the fingerprint of the user after 42 days.
But even that should be allowed to decide the user. 
Automatic deletion is always a hairy matter.

For example, if you are at a party and there are some pretty people who feel like girls and do not want to dance, but just watch others dance, then you can not exclude people just because they do not want to dance.

**Comment by iNPUTmice** [comment]
> At the moment in encrypted groups where you only read and do not write a word, after 42 days your own fingerprints are deleted by the other users. 

No. It doesn’t

The feature stale / inactive devices. Inactivity is not determined by not responding to messages in a group chat but by being offline.

**Comment by ecxod** [comment]
And why don't you want to let people decide if they want such a "feature"?

**Comment by iNPUTmice** [comment]
There seem to be a lot of misconception about how that feature work. Let me describe a couple of scenarios and how that feature behaves in each of them.

### Conversations. One device
If you only use XMPP on one device running Conversations no keys will ever be deleted. No matter how active or inactive you are. You can just pretend the feature doesn’t exist at all and go on with your life. 

### Conversations. Buying a new device.
If you install Conversations on a new device and factory reset and sell your old device (or put it into a drawer never to be seen again) the new device will eventually (after 42 days) recognize that the old device is gone and remove the keys. Note it's not your contacts making a decision about your old device it is your Conversations making a decision about your old device.

This is pretty much what the feature was designed for in the first place. We don’t want the old, unused device cluttering up the fingerprint list.

### Conversations on phone. Read only Conversations on tablet.
Imagine you have Conversations on your phone and another Conversations on your tablet. The tablet is essentially a read only device because you never actually use it. It is turned on but it just lies there on your coffee table.

As in the previous scenario your Conversations on your phone will, after 42 days, think that the other device (the tablet) is inactive and delete the device from the list. **However** since the tablet is turned on it will **immediately realize that and re-announce itself**. The tablet’s key will only be gone for a few seconds and afterwards everything is back to normal and the 42 day timer starts again.

### Conversations on phone. Read only Conversations on table with dead battery.

This is a variant of the previous scenario but here your tablet runs out of battery. So your tablet runs out of battery and you turn it on after **50 days**.  You will have lost access to the chat history of the last 8 days (50-42). However once it turns back on you will automatically receive subsequent message. You don’t have to do anything.

### One device. Turned of for 6 month.

A variant of the first scenario. You have one device but because you have been on vacation for 6 month and didn’t bring your phone you only turn it on after 6 month: Nothing will have happened and you have access to your full history. Discarding old devices is an active process and if there is no device turned on that can do this it won’t happen.



Essentially the "42 day feature" is akin to pressing the 'Clear devices' button after 42 days. The clear devices button has a dialog explaining it's behaviour. You can test this. And if you have other devices running at the same time you'll also see how they'll re-announce themselves automatically.

**Comment by m3thm4th** [comment]
This is not a decision Conversations should make automatically, the user should be able to delete old/unused keys at will, which is not possible until #3253 won't be fixed
