### ISSUE TITLE
Sharing images with wrong extensions

### ISSUE THREAD

**Issue by gjedeer** [iNPUTmice/Conversations#4228]
Steps to reproduce:
1. Visit https://www.meteo.pl/um/metco/mgram_pict.php?ntype=0u&row=411&col=207&lang=pl in Fennec or Bromite (I guess any other browser will work too)
2. Share Image to Conversations. The full image, not the link.
3. Try viewing the image uploaded to your contact

Expected: The image pops up
What happens: "Open File" button is displayed, when you click it, it displays an arbitrary selection of apps installed on your phone.

"Copy Original URL" in Conversations reveals that the file uploaded to HTTP ends with .php

The original site serves the correct Content-Type, so I guess Conversations would need to change the extension of the uploaded file according to the Content-Type:

```
Content-Type: image/png
```

This happens more often than just on this one website, it's just an example that's easy to reproduce.

**Comment by iNPUTmice** [comment]
Firefox doesn’t expose the content type. Neither in the Intent nor on the FileProvider Uri.

Or rather it exposes it as `application/octet-stream` that's why we try to fall back to using the file name (which is not helpfull in the particular case.

`cleanedUris=[content://org.mozilla.firefox.feature.downloads.fileprovider/mediaShareCache/1825338702.php], type=application/octet-stream`

Firefox needs to expose the correct mime type on the file provider.

**Comment by gjedeer** [comment]
Thanks, opened an issue with Firefox.
