### ISSUE TITLE
Fallback to jingle file transfer when http upload user quota is exhausted

### ISSUE THREAD

**Issue by STPKITT** [iNPUTmice/Conversations#4341]
A contact of mine recently contacted me stating that she couldn't sent any pictures anymore.
Conversations would show the error message "not allowed". By logging into her webinterface on the XMPP server I found out that the issue was that her user quota for stored http upload files was exhausted.
This is a situation where a user that's not into IT hits the wall which is a situation that should be avoided at all cost to avoid such users quitting the network.
While I got to know that the user quota getting exhausted is a server config issue I still think that Conversations should provide an automatic workaround for that situation which would be to switch to jingle uploading once http uploading fails.

**Comment by licaon-kter** [comment]
Is that 'not allowed' for one case only? Or everytime you encounter is C should switch to Jingle? 

Shouldn't the user be made aware of the issue too? How?

**Comment by STPKITT** [comment]
I don't know about that "not allowed" error message really, but it's pretty awful. The jabber.at admin yesterday provided me informations about how http upload gets implemented on the server and judging by that the quota management isn't universally the same and neither are error messages provided by the different servers or rather server http upload implementations.
Anyway, to cater for the non-IT crowd Conversations probably shouldn't care about the details/error reasons and provide a comfortable aka automatic workaround.

**Comment by iNPUTmice** [comment]
Jingle File Transfer is not a viable fallback. It doesn’t work with multiple devices, it doesn’t work in groups. It doesn’t work if the recipient is offline.
I will probably add a fall back for the rare cases when the recipient is online with exactly one device but this is not going to fix your issue. Your issue is with your XMPP provider. Other XMPP providers just automatically discard old files if the accumulated size reaches a threshold and/or generally have higher limits. It's not like any other messenger out there has any quotas. (Or at least none the average user is going to reach.)
