### ISSUE TITLE
After inviting to a conference add conference to bookmarks as default

### ISSUE THREAD

**Issue by kriztan** [iNPUTmice/Conversations#937]
I think it is useful to add a conference automatically to bookmarks after getting invited. To me it has already happened that I accidentally left a conference. And then the conference is not in the bookmarks and I have to ask one of the participants to reinvite me or I have to reenter the conference name.

**Comment by Natanji** [comment]
That doesn't seem like a very good idea since an adversary could just spam the user with invites to conferences, and they would all clutter the bookmarks...

**Comment by sokai** [comment]
I like the idea of @kriztan (many of my peers swipe open conversations out, because they do not understand the UI) but I understand the argument of @Natanji.

So there should IMHO be the following implementation:
1. Add the auto-bookmark for new MUCs.
2. Make an option to disable that feture available.
(3. Make an record in MUC options to add the MUC to bookmarks, too! ATM I can not see any possibility to add a MUC, I was invited in, to my bookmarks …) 

Thanks and best regards!
