### ISSUE TITLE
Private message in MUC which is only open in another client

### ISSUE THREAD

**Issue by SamWhited** [iNPUTmice/Conversations#951]
When a private message is received in a MUC which you are joined in another client (but do not have open in Conversations), Conversations shows the message in a new Conversation with the name of the MUC (not the member in the MUC that sent you the message).

An easy way to test:

Join the prosody group chat in another client (but not in Conversations), open a private message with the bot (HAL) and send it something (eg. `!version siacs.eu`). It will send back a message which will appear in Conversations as being from "prosody" (`prosody@conference.prosody.im`).

**Comment by iNPUTmice** [comment]
This is a bit tricky because Conversations has now way of knowing that this (carbon copied) messages originated in a MUC. I think prosody 0.10 has started to tag messages with an <x xmlns="...muc..."> but that is fairly recent and only for prosody. (I'm wondering if prosody will even send out carbons in that case)

what would your proposed solution for that be? not show the message? open a conference conversations, show the message private message in there but not join the conference?

**Comment by SamWhited** [comment]
Yah, I'm not sure what the expected behavior is here. Maybe treat any JID with no localpart (but with a resource) as if it were a MUC (use the RP as a nick)?

I think it makes the most sense to separate ALL muc private conversations out into separate conversations (instead of using the current "whispered" prefix), but I think this was discussed before and decided against for some reason? That was before I started working on the project I think though, I just vaguely remember reading an issue about it or something. Will look later.

**Comment by iNPUTmice** [comment]
> I think it makes the most sense to separate ALL muc private conversations out into separate conversations (instead of using the current "whispered" prefix), but I think this was discussed before and decided against for some reason?

I don't think this has ever been discussed. Not really at least.
But I don't like private messages at all. They get stale if either one of the participants leaves a room, file transfer doesn't really work. OTR doesn't really work. If we were to treat them as normal conversations we would have to explain why stuff like this doesn't work. I kinda wanna get rid of them in favour of having non-anonyoums chat rooms and just starting normal jid-to-jid conversations from there. (At least for your usual 'couple of friends in a room' style conferences.)

That's why I hid that whisper stuff away a bit. And that's why there isn't a really why of initiating 'whispers'. For me that's just being somewhat compatible with the rest of the world. I mean you can not not have it at all.

**Comment by SamWhited** [comment]
Interesting; good idea — that would make things a lot easier in general.

**Comment by andrewd18** [comment]
If you intend to keep whispers as a feature, I would also like to see a long-press on a name start a whole new conversation tab. Trying to keep track of one or more simultaneous whisper conversations is hard. Trying to keep track of whispers in an active, scrolling chat room is nearly impossible. Meanwhile, Pidgin opens a new tab for each MUC user whispering you, which makes following multiple whispers at once easy.

**Comment by Aravinthu** [comment]
Group file sharing not available in this version any help
